// Package nginx renders the desired configuration into nginx config files.
//
// Layout of the rendered file set (paths relative to the release root; all
// includes are relative so they resolve against the directory of nginx.conf):
//
//	nginx.conf                       main file: globals, http {} and stream {}
//	snippets/*.conf                  shared snippets (proxy headers, TLS profiles, …)
//	conf.d/00-global.conf            http-level maps/zones (blocklist, rate limits, geo)
//	conf.d/10-default.conf           default server + stub_status
//	conf.d/hosts/<domain>.conf       one file per enabled proxy host
//	conf.d/redirects/<domain>.conf   redirect servers
//	streams/<name>.conf              stream {} servers
//	htpasswd/<accessListId>          basic-auth users (bcrypt)
//
// Output is deterministic for a given snapshot and env so config hashes are stable.
package nginx

import (
	"fmt"
	"net"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/instantoffr/relay/internal/agent"
	"github.com/instantoffr/relay/internal/model"
	"github.com/instantoffr/relay/internal/render"
)

// Render produces every nginx file (nginx.conf, conf.d/…, htpasswd/…).
func Render(snap *model.Snapshot, env render.Env) (agent.Files, error) {
	r := newRenderer(snap, env)
	return r.all()
}

// RenderHost renders the server block(s) of one proxy host (which may be a
// draft not yet saved in snap) for previews.
func RenderHost(snap *model.Snapshot, host *model.ProxyHost, env render.Env) (string, error) {
	s := *snap
	s.Hosts = replaceHost(snap.Hosts, host)
	r := newRenderer(&s, env)
	h := *host
	h.Enabled = true
	out := r.hostFile(&h)
	return out, r.err()
}

// RenderStream renders the stream server block(s) of one stream for previews.
func RenderStream(snap *model.Snapshot, stream *model.Stream, env render.Env) (string, error) {
	r := newRenderer(snap, env)
	st := *stream
	st.Enabled = true
	out := r.streamFile(&st)
	return out, r.err()
}

// WithHost returns a copy of snap where host replaces the entity with the
// same id (or is appended when new). Used to validate drafts.
func WithHost(snap *model.Snapshot, host *model.ProxyHost) *model.Snapshot {
	s := *snap
	s.Hosts = replaceHost(snap.Hosts, host)
	return &s
}

// WithStream is WithHost for streams.
func WithStream(snap *model.Snapshot, stream *model.Stream) *model.Snapshot {
	s := *snap
	s.Streams = make([]model.Stream, 0, len(snap.Streams)+1)
	found := false
	for _, x := range snap.Streams {
		if stream.ID != "" && x.ID == stream.ID {
			s.Streams = append(s.Streams, *stream)
			found = true
			continue
		}
		s.Streams = append(s.Streams, x)
	}
	if !found {
		s.Streams = append(s.Streams, *stream)
	}
	return &s
}

func replaceHost(hosts []model.ProxyHost, host *model.ProxyHost) []model.ProxyHost {
	out := make([]model.ProxyHost, 0, len(hosts)+1)
	found := false
	for _, x := range hosts {
		if host.ID != "" && x.ID == host.ID {
			out = append(out, *host)
			found = true
			continue
		}
		out = append(out, x)
	}
	if !found {
		out = append(out, *host)
	}
	return out
}

// ---------------------------------------------------------------- renderer

const header = "# Generated by Relay — do not edit. Changes are overwritten on the next apply.\n"

// Paths inside the engine container (Alpine nginx packages).
const (
	mimeTypes    = "/etc/nginx/mime.types"
	pidFile      = "/run/nginx/nginx.pid"
	cacheDir     = "/var/cache/nginx/relay"
	caBundle     = "/etc/ssl/certs/ca-certificates.crt"
	authLocation = "/.relay/auth"
)

// StubStatusAddr is where the local stub_status server listens (the apply
// service sets it from $RELAY_NGINX_STATUS_PORT; the nginx agent's bootstrap
// config uses the same variable).
var StubStatusAddr = "127.0.0.1:18080"

type renderer struct {
	snap      *model.Snapshot
	env       render.Env
	certs     map[string]*model.Certificate
	lists     map[string]*model.AccessList
	hosts     map[string]*model.ProxyHost
	backends  map[string]*model.Backend
	httpPort  int
	httpsPort int
	errs      []string
}

func newRenderer(snap *model.Snapshot, env render.Env) *renderer {
	r := &renderer{
		snap: snap, env: env,
		certs: map[string]*model.Certificate{}, lists: map[string]*model.AccessList{},
		hosts: map[string]*model.ProxyHost{}, backends: map[string]*model.Backend{},
		httpPort: snap.General.HTTPPort, httpsPort: snap.General.HTTPSPort,
	}
	if r.httpPort <= 0 {
		r.httpPort = 80
	}
	if r.httpsPort <= 0 {
		r.httpsPort = 443
	}
	if r.env.Modules == nil {
		r.env.Modules = map[string]bool{}
	}
	for i := range snap.Certificates {
		r.certs[snap.Certificates[i].ID] = &snap.Certificates[i]
	}
	for i := range snap.AccessLists {
		r.lists[snap.AccessLists[i].ID] = &snap.AccessLists[i]
	}
	for i := range snap.Hosts {
		r.hosts[snap.Hosts[i].ID] = &snap.Hosts[i]
	}
	for i := range snap.Backends {
		r.backends[snap.Backends[i].ID] = &snap.Backends[i]
	}
	return r
}

func (r *renderer) fail(format string, args ...any) {
	r.errs = append(r.errs, fmt.Sprintf(format, args...))
}

func (r *renderer) err() error {
	if len(r.errs) == 0 {
		return nil
	}
	return fmt.Errorf("nginx render: %s", strings.Join(r.errs, "; "))
}

func (r *renderer) mod(name string) bool { return r.env.Modules[name] }

// enabledHosts returns enabled hosts sorted by first domain, then id.
func (r *renderer) enabledHosts() []*model.ProxyHost {
	var out []*model.ProxyHost
	for i := range r.snap.Hosts {
		if h := &r.snap.Hosts[i]; h.Enabled && len(h.Domains) > 0 {
			out = append(out, h)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Domains[0] != out[j].Domains[0] {
			return out[i].Domains[0] < out[j].Domains[0]
		}
		return out[i].ID < out[j].ID
	})
	return out
}

func (r *renderer) all() (agent.Files, error) {
	files := agent.Files{}
	hosts := r.enabledHosts()

	files["snippets/proxy-headers.conf"] = proxyHeadersSnippet
	files["snippets/acme-challenge.conf"] = r.acmeSnippet()
	files["snippets/block-exploits.conf"] = blockExploitsSnippet
	for _, p := range []string{"modern", "intermediate", "old"} {
		files["snippets/tls-"+p+".conf"] = header + tlsProfiles[p]
	}
	files["conf.d/00-global.conf"] = r.globalConf(hosts)
	files["conf.d/10-default.conf"] = r.defaultConf()
	for name, body := range r.errorPageFiles(hosts) {
		files[name] = body
	}

	used := map[string]bool{}
	for _, h := range hosts {
		name := uniqueName("conf.d/hosts/", h.Domains[0], h.ID, used)
		files[name] = r.hostFile(h)
	}
	for _, g := range r.redirectGroups() {
		name := uniqueName("conf.d/redirects/", g.domains[0], g.redirects[0].ID, used)
		files[name] = r.redirectFile(g)
	}
	streamServers := 0
	if r.mod("stream") {
		streams := r.enabledStreams()
		for _, s := range streams {
			name := uniqueName("streams/", s.Name, s.ID, used)
			content := r.streamFile(s)
			files[name] = content
			streamServers += strings.Count(content, "set $relay_stream_id")
		}
	} else if len(r.enabledStreams()) > 0 {
		r.fail("streams need the nginx stream module, which this nginx build does not provide")
	}
	files["nginx.conf"] = r.mainConf(streamServers > 0)
	for i := range r.snap.AccessLists {
		al := &r.snap.AccessLists[i]
		if al.BasicAuth.Enabled {
			files["htpasswd/"+safeID(al.ID)] = htpasswd(al)
		}
	}
	return files, r.err()
}

func uniqueName(dir, base, id string, used map[string]bool) string {
	n := fileSafe(base)
	if n == "" {
		n = fileSafe(id)
	}
	name := dir + n + ".conf"
	if used[name] {
		name = dir + n + "-" + fileSafe(id) + ".conf"
	}
	used[name] = true
	return name
}

var fileSafeRe = regexp.MustCompile(`[^a-z0-9._-]+`)

func fileSafe(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = strings.ReplaceAll(s, "*", "_wildcard")
	s = fileSafeRe.ReplaceAllString(s, "-")
	s = strings.Trim(s, ".-")
	if len(s) > 100 {
		s = s[:100]
	}
	return s
}

var idSafeRe = regexp.MustCompile(`[^a-z0-9_]+`)

// safeID turns an entity id into something usable in zone and variable names.
func safeID(id string) string {
	s := idSafeRe.ReplaceAllString(strings.ToLower(id), "_")
	if s == "" {
		return "x"
	}
	return s
}

// ---------------------------------------------------------------- writer

type writer struct {
	b   strings.Builder
	ind int
}

func (w *writer) l(format string, args ...any) {
	if format == "" {
		w.b.WriteByte('\n')
		return
	}
	w.b.WriteString(strings.Repeat("    ", w.ind))
	if len(args) > 0 {
		fmt.Fprintf(&w.b, format, args...)
	} else {
		w.b.WriteString(format)
	}
	w.b.WriteByte('\n')
}

func (w *writer) open(format string, args ...any) {
	w.l(format+" {", args...)
	w.ind++
}

func (w *writer) close() {
	w.ind--
	w.l("}")
}

func (w *writer) raw(text string) {
	for _, line := range strings.Split(strings.TrimRight(text, "\n"), "\n") {
		if strings.TrimSpace(line) == "" {
			w.b.WriteByte('\n')
			continue
		}
		w.b.WriteString(strings.Repeat("    ", w.ind))
		w.b.WriteString(strings.TrimRight(line, " \t\r"))
		w.b.WriteByte('\n')
	}
}

func (w *writer) String() string { return w.b.String() }

var bareRe = regexp.MustCompile(`^[A-Za-z0-9._~:/?\[\]@!$&()*+,=%^|-]+$`)

// q quotes an nginx argument when needed.
func q(s string) string {
	if s != "" && bareRe.MatchString(s) {
		return s
	}
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", " ", "\r", " ").Replace(s) + `"`
}

// comment sanitises text for a # comment.
func comment(s string) string {
	return strings.NewReplacer("\n", " ", "\r", " ").Replace(s)
}

// ---------------------------------------------------------------- nginx.conf

func (r *renderer) mainConf(streamServers bool) string {
	w := &writer{}
	w.raw(header)
	// Only modules the agent reported as dynamic need load_module; the
	// official nginx image compiles stream, http_v3 and auth_request in.
	loaded := false
	for _, m := range []string{"stream", "geoip2"} {
		if path := r.env.ModulePaths[m]; path != "" && r.mod(m) {
			w.l("load_module %s;", path)
			loaded = true
		}
	}
	if loaded {
		w.l("")
	}
	w.l("user nginx;")
	w.l("worker_processes auto;")
	w.l("worker_rlimit_nofile 65535;")
	w.l("pcre_jit on;")
	w.l("pid %s;", pidFile)
	w.l("error_log %s warn;", r.logPath(ErrorLogFile))
	w.l("error_log stderr warn;")
	w.l("")
	w.open("events")
	w.l("worker_connections 8192;")
	w.l("multi_accept on;")
	w.close()
	w.l("")
	w.open("http")
	w.l("include %s;", mimeTypes)
	w.l("default_type application/octet-stream;")
	w.l("")
	w.l("sendfile on;")
	w.l("tcp_nopush on;")
	w.l("tcp_nodelay on;")
	w.l("server_tokens off;")
	w.l("keepalive_timeout 65s;")
	w.l("types_hash_max_size 2048;")
	w.l("server_names_hash_bucket_size 128;")
	w.l("server_names_hash_max_size 4096;")
	w.l("variables_hash_bucket_size 128;")
	w.l("map_hash_bucket_size 128;")
	w.l("client_max_body_size 1m;")
	w.l("")
	w.l("ssl_session_cache shared:relay_tls:20m;")
	w.l("ssl_session_timeout 1d;")
	w.l("ssl_session_tickets off;")
	w.l("")
	w.l("gzip on;")
	w.l("gzip_vary on;")
	w.l("gzip_proxied any;")
	w.l("gzip_comp_level 5;")
	w.l("gzip_min_length 1024;")
	w.l("gzip_types text/plain text/css text/xml text/javascript application/javascript application/json application/xml application/rss+xml application/atom+xml image/svg+xml font/ttf font/otf;")
	w.l("")
	w.raw(HTTPLogFormat)
	w.l("access_log %s relay_json;", r.logPath(AccessLogFile))
	w.l("")
	w.open("map $http_upgrade $connection_upgrade")
	w.l("default upgrade;")
	w.l("'' close;")
	w.close()
	w.l("")
	w.l("proxy_cache_path %s levels=1:2 keys_zone=relay_assets:32m max_size=1g inactive=30d use_temp_path=off;", cacheDir)
	w.l("")
	w.l("include conf.d/*.conf;")
	w.l("include conf.d/hosts/*.conf;")
	w.l("include conf.d/redirects/*.conf;")
	w.close()
	if r.mod("stream") {
		w.l("")
		w.open("stream")
		w.raw(StreamLogFormat)
		w.l("access_log %s relay_stream_json;", r.logPath(StreamAccessLogFile))
		if !streamServers {
			// The log format references $relay_stream_id; stream servers declare
			// it with `set`, so without any server it must exist another way.
			w.l("")
			w.open("map $protocol $relay_stream_id")
			w.l("default \"\";")
			w.close()
		}
		w.l("")
		w.l("include streams/*.conf;")
		w.close()
	} else {
		w.l("")
		w.l("# The stream block is omitted: the nginx stream module is not available.")
	}
	return w.String()
}

func (r *renderer) logPath(name string) string {
	dir := r.env.LogDir
	if dir == "" {
		dir = "/var/log/relay"
	}
	return strings.TrimRight(dir, "/") + "/" + name
}

// ---------------------------------------------------------------- snippets

const proxyHeadersSnippet = header + `proxy_http_version 1.1;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Request-ID $request_id;
`

func (r *renderer) acmeSnippet() string {
	root := r.env.ACMEWebroot
	if root == "" {
		root = "/data/acme"
	}
	return header + `# ACME HTTP-01 challenges are always answered from the webroot.
location ^~ /.well-known/acme-challenge/ {
    root ` + q(root) + `;
    default_type text/plain;
    auth_basic off;
    allow all;
    try_files $uri =404;
}
`
}

const blockExploitsSnippet = header + `# Block common exploit and scanner probes.
if ($request_uri ~* "(\.\./|\.\.%2f|%2e%2e|%00|/etc/passwd|/proc/self/environ)") {
    return 403;
}
if ($request_uri ~* "/(\.env|\.git/|\.svn/|\.hg/|\.DS_Store|wp-config\.php\.bak|vendor/phpunit/|boaform/|HNAP1|cgi-bin/.*\.(sh|pl|cgi))") {
    return 403;
}
if ($query_string ~* "(<|%3C)[^>]*script[^<]*(>|%3E)") {
    return 403;
}
if ($query_string ~* "(union[^a-z]+(all[^a-z]+)?select|information_schema|base64_(en|de)code\(|GLOBALS(=|\[|%[0-9A-Z]{0,2})|_REQUEST(=|\[|%[0-9A-Z]{0,2})|mosConfig_)") {
    return 403;
}
if ($http_user_agent ~* "(sqlmap|nikto|masscan|zgrab|dirbuster|wpscan|acunetix|nessus|nmap scripting engine)") {
    return 403;
}
`

// Mozilla SSL configuration generator profiles (nginx, OpenSSL 3).
var tlsProfiles = map[string]string{
	"modern": `# Mozilla "modern": TLS 1.3 only.
ssl_protocols TLSv1.3;
ssl_ecdh_curve X25519:prime256v1:secp384r1;
ssl_prefer_server_ciphers off;
`,
	"intermediate": `# Mozilla "intermediate": TLS 1.2 + 1.3, recommended for general use.
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ecdh_curve X25519:prime256v1:secp384r1;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
ssl_prefer_server_ciphers off;
`,
	"old": `# Mozilla "old": maximum compatibility for legacy clients.
ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:@SECLEVEL=0;
ssl_prefer_server_ciphers on;
`,
}

// ---------------------------------------------------------------- http globals

func (r *renderer) globalConf(hosts []*model.ProxyHost) string {
	w := &writer{}
	w.raw(header)
	w.l("# Global deny list (Logs → Block IP). Every server returns 403 for these clients.")
	w.open("geo $relay_blocked")
	w.l("default 0;")
	entries := append([]model.BlockEntry(nil), r.snap.Blocklist.Entries...)
	sort.SliceStable(entries, func(i, j int) bool { return entries[i].CIDR < entries[j].CIDR })
	seen := map[string]bool{}
	for _, e := range entries {
		cidr := strings.TrimSpace(e.CIDR)
		if !validCIDR(cidr) || seen[cidr] {
			if !seen[cidr] {
				w.l("# skipped invalid entry %s", comment(cidr))
			}
			continue
		}
		seen[cidr] = true
		w.l("%s 1;", cidr)
	}
	w.close()

	// GeoIP2 country lookup, shared by all geo-blocked hosts.
	geoHosts := []*model.ProxyHost{}
	for _, h := range hosts {
		if h.GeoBlock.Enabled && len(h.GeoBlock.AllowCountries) > 0 {
			geoHosts = append(geoHosts, h)
		}
	}
	if len(geoHosts) > 0 {
		w.l("")
		if r.geoAvailable() {
			w.open("geoip2 %s", q(r.env.GeoIPCountry))
			w.l("auto_reload 60m;")
			w.l("$relay_geo_country country iso_code;")
			w.close()
		} else {
			w.l("# Geo-blocking is configured on %d host(s) but skipped: %s", len(geoHosts), r.geoUnavailableReason())
		}
	}

	for _, h := range sortedByID(hosts) {
		sid := safeID(h.ID)
		if h.Maintenance.Enabled {
			if al := r.lists[h.Maintenance.BypassAccessListID]; al != nil {
				w.l("")
				w.l("# Maintenance for %s: 1 = show the maintenance page, 0 = bypass (access list %s)", comment(h.Domains[0]), comment(al.Name))
				r.geoFromList(w, "$relay_maint_"+sid, al, "0", "1")
			}
		}
		if h.RateLimit.Enabled && h.RateLimit.RequestsPerSecond > 0 {
			w.l("")
			w.l("# Rate limit for %s", comment(h.Domains[0]))
			key := "$binary_remote_addr"
			if al := r.lists[h.RateLimit.ExemptAccessListID]; al != nil {
				w.open("geo $relay_rl_exempt_%s", sid)
				def := "0"
				for _, rule := range al.Rules {
					cidr := strings.TrimSpace(rule.CIDR)
					if strings.EqualFold(cidr, "all") {
						if rule.Action == "allow" {
							def = "1"
						}
						continue
					}
					if !validCIDR(cidr) {
						continue
					}
					if rule.Action == "allow" {
						w.l("%s 1;", cidr)
					} else {
						w.l("%s 0;", cidr)
					}
				}
				w.l("default %s;", def)
				w.close()
				w.open("map $relay_rl_exempt_%s $relay_rl_key_%s", sid, sid)
				w.l("1 \"\";")
				w.l("default $binary_remote_addr;")
				w.close()
				key = "$relay_rl_key_" + sid
			}
			w.l("limit_req_zone %s zone=relay_rl_%s:10m rate=%dr/s;", key, sid, h.RateLimit.RequestsPerSecond)
		}
		if h.GeoBlock.Enabled && len(h.GeoBlock.AllowCountries) > 0 && r.geoAvailable() {
			w.l("")
			w.l("# Countries allowed for %s (unknown/private addresses are allowed)", comment(h.Domains[0]))
			w.open("map $relay_geo_country $relay_geo_allow_%s", sid)
			w.l("default 0;")
			w.l("\"\" 1;")
			countries := append([]string(nil), h.GeoBlock.AllowCountries...)
			sort.Strings(countries)
			for _, c := range countries {
				c = strings.ToUpper(strings.TrimSpace(c))
				if len(c) == 2 {
					w.l("%s 1;", c)
				}
			}
			w.close()
		}
	}
	return w.String()
}

func sortedByID(hosts []*model.ProxyHost) []*model.ProxyHost {
	out := append([]*model.ProxyHost(nil), hosts...)
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func (r *renderer) geoAvailable() bool { return r.mod("geoip2") && r.env.GeoIPCountry != "" }

func (r *renderer) geoUnavailableReason() string {
	if !r.mod("geoip2") {
		return "the nginx geoip2 module is not available"
	}
	return "no GeoLite2-Country database found"
}

func validCIDR(s string) bool {
	if _, _, err := net.ParseCIDR(s); err == nil {
		return true
	}
	return net.ParseIP(s) != nil
}

// ---------------------------------------------------------------- TLS helpers

// usableCert returns the certificate when it has been issued (NotAfter set,
// PEM files written). Status is not used: a certificate whose renewal failed
// keeps serving its existing files; pending certificates get no TLS yet.
func (r *renderer) usableCert(id string) (*model.Certificate, string) {
	if id == "" {
		return nil, ""
	}
	c := r.certs[id]
	if c == nil {
		return nil, "certificate " + id + " does not exist"
	}
	if c.NotAfter != nil && !c.NotAfter.IsZero() {
		return c, ""
	}
	if c.Status != "" && c.Status != model.CertStatusValid {
		return nil, fmt.Sprintf("certificate %s has not been issued yet (%s)", c.Name, c.Status)
	}
	return nil, fmt.Sprintf("certificate %s has not been issued yet", c.Name)
}

func (r *renderer) cipherProfile(host string) string {
	for _, p := range []string{host, r.snap.TLS.CipherProfile} {
		if _, ok := tlsProfiles[p]; ok {
			return p
		}
	}
	return "intermediate"
}

func (r *renderer) hstsHeader(mode string) string {
	h := r.snap.TLS.HSTS
	on := h.Enabled
	switch mode {
	case "on":
		on = true
	case "off":
		on = false
	}
	if !on {
		return ""
	}
	age := h.MaxAgeSeconds
	if age <= 0 {
		age = 15768000
	}
	v := "max-age=" + strconv.Itoa(age)
	if h.IncludeSubdomains {
		v += "; includeSubDomains"
	}
	if h.Preload {
		v += "; preload"
	}
	return v
}

func (r *renderer) http3For(h *model.ProxyHost) bool {
	on := r.snap.General.HTTP3
	if h.HTTP3 != nil {
		on = *h.HTTP3
	}
	return on && r.mod("http_v3")
}

// quicEnabled reports whether any TLS server listens on QUIC (then the
// default server carries the single `reuseport` listen).
func (r *renderer) quicEnabled() bool {
	if !r.mod("http_v3") {
		return false
	}
	for _, h := range r.enabledHosts() {
		if c, _ := r.usableCert(h.CertificateID); c != nil && r.http3For(h) {
			return true
		}
	}
	return false
}

func (r *renderer) listenHTTP(w *writer, def bool) {
	suffix := ""
	if def {
		suffix = " default_server"
	}
	w.l("listen %d%s;", r.httpPort, suffix)
	if r.mod("ipv6") {
		w.l("listen [::]:%d%s;", r.httpPort, suffix)
	}
}

func (r *renderer) listenHTTPS(w *writer, def, quic bool) {
	suffix := ""
	if def {
		suffix = " default_server"
	}
	w.l("listen %d ssl%s;", r.httpsPort, suffix)
	if r.mod("ipv6") {
		w.l("listen [::]:%d ssl%s;", r.httpsPort, suffix)
	}
	if quic {
		reuse := ""
		if def {
			reuse = " reuseport"
		}
		w.l("listen %d quic%s%s;", r.httpsPort, reuse, suffix)
		if r.mod("ipv6") {
			w.l("listen [::]:%d quic%s%s;", r.httpsPort, reuse, suffix)
		}
	}
}

func (r *renderer) tlsDirectives(w *writer, certID string, c *model.Certificate, profile string, http2 bool) {
	if http2 {
		w.l("http2 on;")
	}
	var full, key string
	if c == nil {
		full, key = r.env.DefaultCertPaths()
	} else {
		full, key = r.env.CertPaths(certID)
	}
	w.l("ssl_certificate %s;", q(full))
	w.l("ssl_certificate_key %s;", q(key))
	w.l("include snippets/tls-%s.conf;", profile)
	if c != nil && r.snap.TLS.OCSPStapling && c.Provider == model.CertCustom {
		w.l("ssl_stapling on;")
		w.l("ssl_stapling_verify on;")
	}
}

func (r *renderer) blocked(w *writer) {
	w.open("if ($relay_blocked)")
	w.l("return 403;")
	w.close()
}

// ---------------------------------------------------------------- default server

const notFoundPage = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>404 Not Found</title></head><body style="margin:0;height:100vh;display:flex;align-items:center;justify-content:center;font:14px system-ui,sans-serif;color:#666;background:#fafaf9">404 · Not found</body></html>`

func (r *renderer) defaultConf() string {
	w := &writer{}
	w.raw(header)
	dh := r.snap.DefaultHost
	w.l("# Default server: requests for unknown domains or bare IPs (action: %s).", comment(orDefault(dh.Action, "close")))
	w.open("server")
	r.listenHTTP(w, true)
	r.listenHTTPS(w, true, r.quicEnabled())
	w.l("server_name _;")
	w.l("set $relay_host_id \"\";")
	r.blocked(w)
	cert, why := r.usableCert(dh.CertificateID)
	if dh.CertificateID != "" && cert == nil {
		w.l("# %s: using the self-signed placeholder", comment(why))
	}
	r.tlsDirectives(w, dh.CertificateID, cert, r.cipherProfile(""), true)
	w.l("")
	w.l("include snippets/acme-challenge.conf;")
	w.l("")
	switch dh.Action {
	case "404":
		w.open("location /")
		w.l("default_type text/html;")
		w.l("return 404 '%s';", notFoundPage)
		w.close()
	case "redirect":
		if strings.TrimSpace(dh.RedirectTo) == "" {
			w.l("# redirect target missing: closing the connection instead")
			w.open("location /")
			w.l("return 444;")
			w.close()
		} else {
			w.open("location /")
			w.l("return 302 %s;", q(strings.TrimSpace(dh.RedirectTo)))
			w.close()
		}
	case "host":
		h := r.hosts[dh.HostID]
		if h == nil || !h.Enabled {
			w.l("# default host %s is missing or disabled: closing the connection instead", comment(dh.HostID))
			w.open("location /")
			w.l("return 444;")
			w.close()
		} else {
			w.l("# Serving proxy host %s", comment(first(h.Domains)))
			r.hostBody(w, h, false)
		}
	default:
		w.open("location /")
		w.l("return 444;")
		w.close()
	}
	w.close()

	w.l("")
	w.l("# Local stub_status endpoint for Relay's metrics collector.")
	w.open("server")
	w.l("listen %s;", StubStatusAddr)
	w.l("server_name _;")
	w.l("set $relay_host_id \"\";")
	w.l("access_log off;")
	w.open("location = /stub_status")
	w.l("stub_status;")
	w.close()
	w.open("location /")
	w.l("return 404;")
	w.close()
	w.close()
	return w.String()
}

func orDefault(s, def string) string {
	if s == "" {
		return def
	}
	return s
}

func first(ss []string) string {
	if len(ss) == 0 {
		return ""
	}
	return ss[0]
}

// ---------------------------------------------------------------- proxy hosts

func (r *renderer) hostFile(h *model.ProxyHost) string {
	w := &writer{}
	w.raw(header)
	w.l("# Proxy host %s (id %s)", comment(strings.Join(h.Domains, ", ")), comment(h.ID))
	names := serverNames(h.Domains)
	cert, why := r.usableCert(h.CertificateID)
	if h.CertificateID != "" && cert == nil {
		w.l("# %s: serving HTTP only until it is valid", comment(why))
	}
	if cert != nil && h.ForceHTTPS {
		w.open("server")
		r.listenHTTP(w, false)
		w.l("server_name %s;", names)
		w.l("set $relay_host_id %s;", q(h.ID))
		r.blocked(w)
		w.l("include snippets/acme-challenge.conf;")
		w.open("location /")
		w.l("return 301 %s;", r.httpsRedirect())
		w.close()
		w.close()
		w.l("")
	}
	w.open("server")
	if cert == nil || !h.ForceHTTPS {
		r.listenHTTP(w, false)
	}
	quic := cert != nil && r.http3For(h)
	if cert != nil {
		r.listenHTTPS(w, false, quic)
	}
	w.l("server_name %s;", names)
	w.l("set $relay_host_id %s;", q(h.ID))
	if cert != nil {
		r.tlsDirectives(w, h.CertificateID, cert, r.cipherProfile(h.CipherProfile), h.HTTP2)
		if v := r.hstsHeader(h.HSTS); v != "" {
			w.l("add_header Strict-Transport-Security %s always;", q(v))
		}
		if quic {
			w.l("add_header Alt-Svc 'h3=\":%d\"; ma=86400' always;", r.httpsPort)
		}
	}
	if cert == nil || !h.ForceHTTPS {
		w.l("include snippets/acme-challenge.conf;")
	}
	r.hostBody(w, h, true)
	w.close()
	return w.String()
}

func (r *renderer) httpsRedirect() string {
	if r.httpsPort == 443 {
		return "https://$host$request_uri"
	}
	return fmt.Sprintf("https://$host:%d$request_uri", r.httpsPort)
}

func serverNames(domains []string) string {
	out := make([]string, 0, len(domains))
	for _, d := range domains {
		d = strings.ToLower(strings.TrimSpace(d))
		if d != "" {
			out = append(out, q(d))
		}
	}
	if len(out) == 0 {
		return "_"
	}
	return strings.Join(out, " ")
}

// hostBody renders everything inside a host's server block after listen /
// server_name / TLS: protections, auth, locations and the custom snippet.
func (r *renderer) hostBody(w *writer, h *model.ProxyHost, custom bool) {
	sid := safeID(h.ID)
	if custom { // the default server already emitted the blocklist check
		r.blocked(w)
	}
	if h.GeoBlock.Enabled && len(h.GeoBlock.AllowCountries) > 0 {
		if r.geoAvailable() {
			w.open("if ($relay_geo_allow_%s = 0)", sid)
			w.l("return 403;")
			w.close()
		} else {
			w.l("# geo-block skipped: %s", r.geoUnavailableReason())
		}
	}
	if h.BlockExploits {
		w.l("include snippets/block-exploits.conf;")
	}
	if h.NoIndex {
		w.l("add_header X-Robots-Tag \"noindex, nofollow\" always;")
	}
	if s := strings.TrimSpace(h.MaxBodySize); s != "" && validSize(s) {
		w.l("client_max_body_size %s;", s)
	}
	if h.ProxyReadTimeout > 0 {
		w.l("proxy_read_timeout %ds;", h.ProxyReadTimeout)
	}
	if h.ProxySendTimeout > 0 {
		w.l("proxy_send_timeout %ds;", h.ProxySendTimeout)
	}
	if h.RateLimit.Enabled && h.RateLimit.RequestsPerSecond > 0 {
		burst := h.RateLimit.Burst
		if burst < 0 {
			burst = 0
		}
		w.l("limit_req zone=relay_rl_%s burst=%d nodelay;", sid, burst)
		w.l("limit_req_status 429;")
	}
	if usesHTTPS(h) {
		w.l("proxy_ssl_server_name on;")
		if h.UpstreamTLSVerify {
			w.l("proxy_ssl_verify on;")
			w.l("proxy_ssl_verify_depth 3;")
			w.l("proxy_ssl_trusted_certificate %s;", caBundle)
		} else {
			w.l("proxy_ssl_verify off;")
		}
	}

	if r.errorPages(w, h) {
		w.open("location ^~ %s", render.ErrorsPath)
		w.l("internal;")
		w.l("alias %s;", q(strings.TrimRight(r.env.ConfDir, "/")+"/errors/"))
		w.close()
	}

	fa := r.forwardAuth(h)
	if fa {
		w.l("")
		w.l("# Forward auth (%s)", comment(orDefault(h.ForwardAuth.Provider, "custom")))
		w.open("location = %s", authLocation)
		w.l("internal;")
		w.l("proxy_pass %s;", q(strings.TrimSpace(h.ForwardAuth.VerifyURL)))
		w.l("proxy_pass_request_body off;")
		w.l("proxy_http_version 1.1;")
		w.l("proxy_set_header Content-Length \"\";")
		w.l("proxy_set_header X-Original-URL $scheme://$http_host$request_uri;")
		w.l("proxy_set_header X-Original-Method $request_method;")
		w.l("proxy_set_header X-Forwarded-Method $request_method;")
		w.l("proxy_set_header X-Forwarded-Proto $scheme;")
		w.l("proxy_set_header X-Forwarded-Host $http_host;")
		w.l("proxy_set_header X-Forwarded-Uri $request_uri;")
		w.l("proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
		w.l("proxy_set_header X-Real-IP $remote_addr;")
		if strings.HasPrefix(strings.ToLower(h.ForwardAuth.VerifyURL), "https://") {
			w.l("proxy_ssl_server_name on;")
		}
		w.close()
		if s := strings.TrimSpace(h.ForwardAuth.SignInURL); s != "" {
			sep := "?"
			if strings.Contains(s, "?") {
				sep = "&"
			}
			w.open("location @relay_signin")
			w.l("return 302 %s;", q(s+sep+"rd=$scheme://$http_host$request_uri"))
			w.close()
		}
	}

	// Locations: user-defined, longest prefix first; "/" always present.
	locs := r.hostLocations(h)
	for _, loc := range locs {
		w.l("")
		r.location(w, h, loc)
	}

	r.injectRedirects(w, h)

	if custom && strings.TrimSpace(h.CustomNginx) != "" {
		w.l("")
		w.l("# Custom nginx snippet")
		w.raw(h.CustomNginx)
	}
}

func usesHTTPS(h *model.ProxyHost) bool {
	if strings.EqualFold(h.Upstream.Scheme, "https") {
		return true
	}
	for _, l := range h.Locations {
		if l.Kind == model.LocationProxy && strings.EqualFold(l.Upstream.Scheme, "https") {
			return true
		}
	}
	return false
}

var sizeRe = regexp.MustCompile(`^[0-9]+[kKmMgG]?$`)

func validSize(s string) bool { return sizeRe.MatchString(s) }

func (r *renderer) forwardAuth(h *model.ProxyHost) bool {
	if !h.ForwardAuth.Enabled || strings.TrimSpace(h.ForwardAuth.VerifyURL) == "" {
		return false
	}
	if len(r.env.Modules) > 0 && !r.mod("auth_request") {
		r.fail("host %s uses forward auth, but nginx lacks the auth_request module", first(h.Domains))
		return false
	}
	return true
}

const acmePath = "/.well-known/acme-challenge/"

// hostLocations returns the host's locations (deduplicated, longest path
// first) with a default "/" when missing, plus "/.well-known/" without
// forward auth when SkipWellKnown is set.
type hostLocation struct {
	model.Location
	skipForwardAuth bool
}

func (r *renderer) hostLocations(h *model.ProxyHost) []hostLocation {
	seen := map[string]bool{acmePath: true}
	out := []hostLocation{}
	for _, l := range h.Locations {
		p := normPath(l.Path)
		if p == "" || seen[p] {
			continue
		}
		seen[p] = true
		l.Path = p
		out = append(out, hostLocation{Location: l})
	}
	if !seen["/"] {
		out = append(out, hostLocation{Location: model.Location{ID: "default", Path: "/", Kind: model.LocationSame, Websockets: h.Websockets}})
	}
	if h.ForwardAuth.Enabled && h.ForwardAuth.SkipWellKnown && !seen["/.well-known/"] {
		out = append(out, hostLocation{Location: model.Location{ID: "well-known", Path: "/.well-known/", Kind: model.LocationSame, Websockets: h.Websockets}, skipForwardAuth: true})
	}
	sort.SliceStable(out, func(i, j int) bool {
		if len(out[i].Path) != len(out[j].Path) {
			return len(out[i].Path) > len(out[j].Path)
		}
		return out[i].Path < out[j].Path
	})
	return out
}

func normPath(p string) string {
	p = strings.TrimSpace(p)
	if p == "" {
		return ""
	}
	if !strings.HasPrefix(p, "/") {
		p = "/" + p
	}
	return p
}

var staticExt = `\.(?:css|js|mjs|map|png|jpe?g|gif|ico|svg|webp|avif|bmp|woff2?|ttf|otf|eot|mp4|webm|ogg|mp3|wav|pdf)$`

func (r *renderer) location(w *writer, h *model.ProxyHost, l hostLocation) {
	w.open("location %s", q(l.Path))
	r.maintenance(w, h, l)
	if l.Kind == model.LocationDeny {
		w.l("return 403;")
		w.close()
		return
	}
	up := h.Upstream
	if l.Kind == model.LocationProxy {
		up = l.Upstream
	}
	websockets := l.Websockets
	if l.Path == "/" && l.ID == "default" {
		websockets = h.Websockets
	}
	r.access(w, h, l)
	rewrite := rewriteFor(l.Path, up.Path, l.StripPrefix)
	if rewrite != "" {
		w.raw(rewrite)
	}
	w.l("include snippets/proxy-headers.conf;")
	if websockets {
		w.l("proxy_set_header Upgrade $http_upgrade;")
		w.l("proxy_set_header Connection $connection_upgrade;")
	}
	if r.forwardAuthActive(h, l) {
		if h.ForwardAuth.PassRemoteUser {
			w.l("proxy_set_header Remote-User $relay_remote_user;")
			w.l("proxy_set_header Remote-Email $relay_remote_email;")
			w.l("proxy_set_header Remote-Name $relay_remote_name;")
		}
		if h.ForwardAuth.PassRemoteGroups {
			w.l("proxy_set_header Remote-Groups $relay_remote_groups;")
		}
	}
	for _, hd := range l.Headers {
		if !headerNameRe.MatchString(hd.Name) {
			continue
		}
		w.l("proxy_set_header %s %s;", hd.Name, q(hd.Value))
	}
	if h.CacheAssets || l.Cache {
		w.open("location ~* %s", q(staticExt))
		r.maintenance(w, h, l)
		w.l("proxy_cache relay_assets;")
		w.l("proxy_cache_valid 200 301 302 30d;")
		w.l("proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;")
		w.l("proxy_cache_lock on;")
		w.l("expires 30d;")
		if rewrite != "" {
			w.raw(rewrite)
		}
		w.l("proxy_pass %s;", upstreamURL(up))
		w.close()
	}
	w.l("proxy_pass %s;", upstreamURL(up))
	w.close()
}

var headerNameRe = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)

func (r *renderer) forwardAuthActive(h *model.ProxyHost, l hostLocation) bool {
	return !l.NoAuth && !l.skipForwardAuth && h.ForwardAuth.Enabled && strings.TrimSpace(h.ForwardAuth.VerifyURL) != "" &&
		(len(r.env.Modules) == 0 || r.mod("auth_request"))
}

// access renders the access list and forward-auth directives of a location.
func (r *renderer) access(w *writer, h *model.ProxyHost, l hostLocation) {
	if l.NoAuth {
		w.l("# no access list or forward auth for this path")
		return
	}
	listID := h.AccessListID
	if l.AccessListID != "" {
		listID = l.AccessListID
	}
	if listID != "" {
		al := r.lists[listID]
		if al == nil {
			w.l("# access list %s no longer exists: denying all", comment(listID))
			w.l("deny all;")
		} else {
			r.accessList(w, al)
		}
	}
	if r.forwardAuthActive(h, l) {
		w.l("auth_request %s;", authLocation)
		if h.ForwardAuth.PassRemoteUser {
			w.l("auth_request_set $relay_remote_user $upstream_http_remote_user;")
			w.l("auth_request_set $relay_remote_email $upstream_http_remote_email;")
			w.l("auth_request_set $relay_remote_name $upstream_http_remote_name;")
		}
		if h.ForwardAuth.PassRemoteGroups {
			w.l("auth_request_set $relay_remote_groups $upstream_http_remote_groups;")
		}
		if strings.TrimSpace(h.ForwardAuth.SignInURL) != "" {
			w.l("error_page 401 = @relay_signin;")
			// A location's own error_page stops the server's from applying.
			r.errorPages(w, h)
		}
	}
}

func (r *renderer) accessList(w *writer, al *model.AccessList) {
	w.l("# access list %s", comment(al.Name))
	hasRules := false
	lastAll := false
	anyAllow := false
	for _, rule := range al.Rules {
		cidr := strings.TrimSpace(rule.CIDR)
		action := "deny"
		if rule.Action == "allow" {
			action = "allow"
		}
		if strings.EqualFold(cidr, "all") {
			w.l("%s all;", action)
			hasRules, lastAll = true, true
			break
		}
		if !validCIDR(cidr) {
			w.l("# skipped invalid rule %s", comment(cidr))
			continue
		}
		w.l("%s %s;", action, cidr)
		hasRules = true
		if action == "allow" {
			anyAllow = true
		}
	}
	if hasRules && anyAllow && !lastAll {
		w.l("deny all;")
	}
	basic := al.BasicAuth.Enabled
	if basic {
		w.l("auth_basic %s;", q(orDefault(al.BasicAuth.Realm, "Restricted")))
		w.l("auth_basic_user_file htpasswd/%s;", safeID(al.ID))
	}
	if hasRules && basic {
		if al.SatisfyAny {
			w.l("satisfy any;")
		} else {
			w.l("satisfy all;")
		}
	}
}

func rewriteFor(locPath, upPath string, strip bool) string {
	base := strings.TrimRight(strings.TrimSpace(upPath), "/")
	if base != "" && !strings.HasPrefix(base, "/") {
		base = "/" + base
	}
	if strip && locPath != "/" {
		prefix := strings.TrimRight(locPath, "/")
		return fmt.Sprintf("rewrite %s %s break;", q("^"+regexp.QuoteMeta(prefix)+"/?(.*)$"), q(base+"/$1"))
	}
	if base != "" {
		return fmt.Sprintf("rewrite ^(.*)$ %s break;", q(base+"$1"))
	}
	return ""
}

func upstreamURL(u model.Upstream) string {
	scheme := strings.ToLower(u.Scheme)
	if scheme != "https" {
		scheme = "http"
	}
	host := strings.TrimSpace(u.Host)
	if ip := net.ParseIP(host); ip != nil && ip.To4() == nil {
		host = "[" + host + "]"
	}
	if u.Port > 0 {
		host += ":" + strconv.Itoa(u.Port)
	}
	return scheme + "://" + host
}

// ---------------------------------------------------------------- redirects

type redirectGroup struct {
	domains   []string
	redirects []*model.Redirect
}

// hostDomains maps domains served by enabled proxy hosts to the host.
func (r *renderer) hostDomains() map[string]*model.ProxyHost {
	out := map[string]*model.ProxyHost{}
	for _, h := range r.enabledHosts() {
		for _, d := range h.Domains {
			out[strings.ToLower(strings.TrimSpace(d))] = h
		}
	}
	return out
}

func isWholeDomain(rd *model.Redirect) bool {
	p := strings.TrimSpace(rd.FromPath)
	return p == "" || p == "/"
}

func (r *renderer) enabledRedirects() []*model.Redirect {
	var out []*model.Redirect
	for i := range r.snap.Redirects {
		rd := &r.snap.Redirects[i]
		if rd.Enabled && len(rd.Domains) > 0 && strings.TrimSpace(rd.To) != "" {
			out = append(out, rd)
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Domains[0] != out[j].Domains[0] {
			return out[i].Domains[0] < out[j].Domains[0]
		}
		if len(out[i].FromPath) != len(out[j].FromPath) {
			return len(out[i].FromPath) > len(out[j].FromPath)
		}
		return out[i].ID < out[j].ID
	})
	return out
}

// redirectGroups groups redirects that need their own server block by domain set.
func (r *renderer) redirectGroups() []redirectGroup {
	hostDomains := r.hostDomains()
	idx := map[string]int{}
	var groups []redirectGroup
	for _, rd := range r.enabledRedirects() {
		domains := normDomains(rd.Domains)
		served := false
		for _, d := range domains {
			if hostDomains[d] != nil {
				served = true
			}
		}
		if served {
			continue // rendered inside the proxy host (path redirects) or skipped
		}
		key := strings.Join(domains, " ")
		i, ok := idx[key]
		if !ok {
			i = len(groups)
			idx[key] = i
			groups = append(groups, redirectGroup{domains: domains})
		}
		groups[i].redirects = append(groups[i].redirects, rd)
	}
	return groups
}

func normDomains(ds []string) []string {
	out := []string{}
	for _, d := range ds {
		d = strings.ToLower(strings.TrimSpace(d))
		if d != "" {
			out = append(out, d)
		}
	}
	sort.Strings(out)
	return out
}

func redirectCode(c int) int {
	switch c {
	case 301, 302, 307, 308:
		return c
	}
	return 301
}

func (r *renderer) redirectFile(g redirectGroup) string {
	w := &writer{}
	w.raw(header)
	var cert *model.Certificate
	certID := ""
	forceHTTPS := false
	for _, rd := range g.redirects {
		w.l("# Redirect %s%s → %s (%d, id %s)", comment(strings.Join(rd.Domains, ", ")), comment(rd.FromPath), comment(rd.To), redirectCode(rd.Code), comment(rd.ID))
		if cert == nil && rd.CertificateID != "" {
			if c, why := r.usableCert(rd.CertificateID); c != nil {
				cert, certID = c, rd.CertificateID
			} else {
				w.l("# %s: serving HTTP only", comment(why))
			}
		}
		if rd.ForceHTTPS {
			forceHTTPS = true
		}
	}
	names := serverNames(g.domains)
	if cert != nil && forceHTTPS {
		w.open("server")
		r.listenHTTP(w, false)
		w.l("server_name %s;", names)
		w.l("set $relay_host_id \"\";")
		r.blocked(w)
		w.l("include snippets/acme-challenge.conf;")
		w.open("location /")
		w.l("return 301 %s;", r.httpsRedirect())
		w.close()
		w.close()
		w.l("")
	}
	w.open("server")
	if cert == nil || !forceHTTPS {
		r.listenHTTP(w, false)
	}
	if cert != nil {
		r.listenHTTPS(w, false, false)
	}
	w.l("server_name %s;", names)
	w.l("set $relay_host_id \"\";")
	r.blocked(w)
	if cert != nil {
		r.tlsDirectives(w, certID, cert, r.cipherProfile(""), true)
	}
	if cert == nil || !forceHTTPS {
		w.l("include snippets/acme-challenge.conf;")
	}
	whole := false
	for _, rd := range g.redirects {
		w.l("")
		if isWholeDomain(rd) {
			if whole {
				continue
			}
			whole = true
			w.open("location /")
			w.l("return %d %s;", redirectCode(rd.Code), q(redirectTarget(rd.To, rd.KeepPath, "$request_uri")))
			w.close()
			continue
		}
		r.pathRedirect(w, rd)
	}
	if !whole {
		w.l("")
		w.open("location /")
		w.l("return 404;")
		w.close()
	}
	w.close()
	return w.String()
}

func redirectTarget(to string, keep bool, suffix string) string {
	to = strings.TrimSpace(to)
	if !keep {
		return to
	}
	return strings.TrimRight(to, "/") + suffix
}

func (r *renderer) pathRedirect(w *writer, rd *model.Redirect) {
	from := strings.TrimRight(normPath(rd.FromPath), "/")
	re := "^" + regexp.QuoteMeta(from) + "(?<relay_rest>/.*)?$"
	w.open("location ~ %s", q(re))
	if rd.KeepPath {
		w.l("return %d %s;", redirectCode(rd.Code), q(redirectTarget(rd.To, true, "$relay_rest$is_args$args")))
	} else {
		w.l("return %d %s;", redirectCode(rd.Code), q(strings.TrimSpace(rd.To)))
	}
	w.close()
}

// injectRedirects renders path redirects for domains served by host h.
func (r *renderer) injectRedirects(w *writer, h *model.ProxyHost) {
	domains := map[string]bool{}
	for _, d := range h.Domains {
		domains[strings.ToLower(strings.TrimSpace(d))] = true
	}
	for _, rd := range r.enabledRedirects() {
		match := false
		for _, d := range rd.Domains {
			if domains[strings.ToLower(strings.TrimSpace(d))] {
				match = true
			}
		}
		if !match {
			continue
		}
		w.l("")
		if isWholeDomain(rd) {
			w.l("# redirect %s → %s skipped: the domain is served by this proxy host", comment(first(rd.Domains)), comment(rd.To))
			continue
		}
		w.l("# Redirect %s → %s", comment(rd.FromPath), comment(rd.To))
		r.pathRedirect(w, rd)
	}
}

// ---------------------------------------------------------------- streams

func (r *renderer) enabledStreams() []*model.Stream {
	var out []*model.Stream
	for i := range r.snap.Streams {
		if s := &r.snap.Streams[i]; s.Enabled {
			out = append(out, s)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Name != out[j].Name {
			return out[i].Name < out[j].Name
		}
		return out[i].ID < out[j].ID
	})
	return out
}

func parsePorts(s string) (lo, hi int, err error) {
	s = strings.TrimSpace(s)
	a, b, isRange := strings.Cut(s, "-")
	lo, err = strconv.Atoi(strings.TrimSpace(a))
	if err != nil {
		return 0, 0, fmt.Errorf("invalid port %q", s)
	}
	hi = lo
	if isRange {
		if hi, err = strconv.Atoi(strings.TrimSpace(b)); err != nil {
			return 0, 0, fmt.Errorf("invalid port range %q", s)
		}
	}
	if lo < 1 || hi > 65535 || hi < lo {
		return 0, 0, fmt.Errorf("invalid port range %q", s)
	}
	return lo, hi, nil
}

func hostPort(host string, port string) string {
	if ip := net.ParseIP(host); ip != nil && ip.To4() == nil {
		return "[" + host + "]:" + port
	}
	return host + ":" + port
}

func (r *renderer) streamFile(s *model.Stream) string {
	w := &writer{}
	w.raw(header)
	w.l("# Stream %s (id %s, %s)", comment(s.Name), comment(s.ID), comment(orDefault(s.Protocol, "tcp")))
	lo, hi, err := parsePorts(s.ListenPorts)
	if err != nil {
		r.fail("stream %s: %v", s.Name, err)
		w.l("# skipped: %s", comment(err.Error()))
		return w.String()
	}
	fwdHost := strings.TrimSpace(s.ForwardHost)
	flo, fhi := lo, hi
	if s.BackendID != "" {
		fe := r.backendFrontend(s.BackendID)
		if fe == "" {
			name := s.BackendID
			if b := r.backends[s.BackendID]; b != nil {
				name = b.Name
			}
			r.fail("stream %s: backend %s has no enabled TCP frontend bound to 127.0.0.1", s.Name, name)
			w.l("# skipped: backend %s has no enabled TCP frontend on 127.0.0.1", comment(name))
			return w.String()
		}
		h, p, _ := net.SplitHostPort(fe)
		fwdHost = h
		flo, _ = strconv.Atoi(p)
		fhi = flo
		w.l("# via HAProxy backend %s (frontend %s)", comment(s.BackendID), fe)
	} else if strings.TrimSpace(s.ForwardPorts) != "" {
		if flo, fhi, err = parsePorts(s.ForwardPorts); err != nil {
			r.fail("stream %s: forward %v", s.Name, err)
			w.l("# skipped: forward %s", comment(err.Error()))
			return w.String()
		}
	}
	if fwdHost == "" {
		r.fail("stream %s: forward host is empty", s.Name)
		w.l("# skipped: forward host is empty")
		return w.String()
	}
	if flo != fhi && fhi-flo != hi-lo {
		r.fail("stream %s: listen range %s and forward range %s differ in size", s.Name, s.ListenPorts, s.ForwardPorts)
		w.l("# skipped: port ranges differ in size")
		return w.String()
	}

	protos := []string{""}
	switch s.Protocol {
	case "udp":
		protos = []string{" udp"}
	case "both":
		protos = []string{"", " udp"}
	}
	addr := strings.TrimSpace(s.ListenAddress)
	listen := func(ports string) {
		for _, p := range protos {
			if addr == "" {
				w.l("listen %s%s;", ports, p)
			} else {
				w.l("listen %s%s;", hostPort(addr, ports), p)
			}
		}
	}
	common := func() {
		w.l("set $relay_stream_id %s;", q(s.ID))
		if t := strings.TrimSpace(s.IdleTimeout); t != "" && timeRe.MatchString(t) {
			w.l("proxy_timeout %s;", t)
		} else {
			w.l("proxy_timeout 10m;")
		}
		w.l("proxy_connect_timeout 10s;")
		if s.ProxyProtocol {
			w.l("proxy_protocol on;")
		}
	}
	ports := strconv.Itoa(lo)
	if hi != lo {
		ports = fmt.Sprintf("%d-%d", lo, hi)
	}
	isIP := net.ParseIP(fwdHost) != nil
	sid := safeID(s.ID)

	switch {
	case flo == fhi: // everything to one port
		w.open("server")
		listen(ports)
		common()
		w.l("proxy_pass %s;", hostPort(fwdHost, strconv.Itoa(flo)))
		w.close()
	case isIP && flo == lo: // same ports 1:1
		w.open("server")
		listen(ports)
		common()
		w.l("proxy_pass %s;", hostPort(fwdHost, "$server_port"))
		w.close()
	case isIP: // shifted range 1:1
		if hi-lo > 5000 {
			r.fail("stream %s: port range too large", s.Name)
			return w.String()
		}
		w.open("map $server_port $relay_stream_port_%s", sid)
		for p := lo; p <= hi; p++ {
			w.l("%d %d;", p, flo+(p-lo))
		}
		w.close()
		w.open("server")
		listen(ports)
		common()
		w.l("proxy_pass %s;", hostPort(fwdHost, "$relay_stream_port_"+sid))
		w.close()
	default: // hostname: one server per port keeps the config resolver-free
		if hi-lo > 1000 {
			r.fail("stream %s: port ranges to a hostname are limited to 1000 ports", s.Name)
			return w.String()
		}
		for p := lo; p <= hi; p++ {
			w.open("server")
			listen(strconv.Itoa(p))
			common()
			w.l("proxy_pass %s;", hostPort(fwdHost, strconv.Itoa(flo+(p-lo))))
			w.close()
		}
	}
	return w.String()
}

var timeRe = regexp.MustCompile(`^[0-9]+(ms|s|m|h|d)?$`)

// backendFrontend returns the 127.0.0.1 bind of the first enabled TCP
// frontend whose default backend is backendID.
func (r *renderer) backendFrontend(backendID string) string {
	fes := append([]model.Frontend(nil), r.snap.Frontends...)
	sort.SliceStable(fes, func(i, j int) bool { return fes[i].CreatedAt.Before(fes[j].CreatedAt) })
	for _, f := range fes {
		if !f.Enabled || f.Mode != "tcp" || f.DefaultBackendID != backendID {
			continue
		}
		h, p, err := net.SplitHostPort(strings.TrimSpace(f.Bind))
		if err != nil || h != "127.0.0.1" {
			continue
		}
		if _, err := strconv.Atoi(p); err != nil {
			continue
		}
		return net.JoinHostPort(h, p)
	}
	return ""
}

// ---------------------------------------------------------------- htpasswd

func htpasswd(al *model.AccessList) string {
	users := append([]model.BasicAuthUser(nil), al.BasicAuth.Users...)
	sort.SliceStable(users, func(i, j int) bool { return users[i].Username < users[j].Username })
	var b strings.Builder
	b.WriteString("# " + comment(al.Name) + "\n")
	for _, u := range users {
		name := strings.TrimSpace(u.Username)
		if name == "" || u.PasswordHash == "" || strings.ContainsAny(name, ":\n") {
			continue
		}
		b.WriteString(name + ":" + strings.TrimSpace(u.PasswordHash) + "\n")
	}
	return b.String()
}

// ---------------------------------------------------------------- error & maintenance pages

// errorPageFiles renders Relay's error pages and each host's maintenance page.
func (r *renderer) errorPageFiles(hosts []*model.ProxyHost) map[string]string {
	out := map[string]string{}
	set := r.snap.ErrorPages.WithDefaults()
	if set.Enabled {
		for _, code := range render.ErrorPageCodes {
			key := fmt.Sprint(code)
			out["errors/"+key+".html"] = render.ErrorPageHTML(set, key, nil)
		}
	}
	for _, h := range hosts {
		if h.Maintenance.Enabled {
			out["errors/maintenance-"+safeID(h.ID)+".html"] = render.ErrorPageHTML(set, "maintenance", &h.Maintenance)
		}
	}
	return out
}

// errorPages renders the error_page directives of a host; it reports whether
// any were written (then the server needs the internal errors location).
func (r *renderer) errorPages(w *writer, h *model.ProxyHost) bool {
	on := r.snap.ErrorPages.Enabled
	if !on && !h.Maintenance.Enabled {
		return false
	}
	if on {
		for _, code := range render.ErrorPageCodes {
			if code == 503 && h.Maintenance.Enabled {
				continue
			}
			w.l("error_page %d %s%d.html;", code, render.ErrorsPath, code)
		}
	}
	if h.Maintenance.Enabled {
		w.l("error_page 503 %smaintenance-%s.html;", render.ErrorsPath, safeID(h.ID))
	}
	return true
}

// maintenance answers a location with 503 while the host is in maintenance
// (the Relay login location keeps working; ACME has its own location).
func (r *renderer) maintenance(w *writer, h *model.ProxyHost, l hostLocation) {
	if !h.Maintenance.Enabled || l.ID == render.PortalLocationID {
		return
	}
	if r.lists[h.Maintenance.BypassAccessListID] != nil {
		w.open("if ($relay_maint_%s)", safeID(h.ID))
		w.l("return 503;")
		w.close()
		return
	}
	w.l("return 503;")
}

// geoFromList renders an access list as an nginx geo map: allowed networks
// get allowed, denied ones denied; "all" sets the default.
func (r *renderer) geoFromList(w *writer, name string, al *model.AccessList, allowed, denied string) {
	w.open("geo %s", name)
	def := denied
	for _, rule := range al.Rules {
		cidr := strings.TrimSpace(rule.CIDR)
		if strings.EqualFold(cidr, "all") {
			if rule.Action == "allow" {
				def = allowed
			} else {
				def = denied
			}
			continue
		}
		if !validCIDR(cidr) {
			continue
		}
		if rule.Action == "allow" {
			w.l("%s %s;", cidr, allowed)
		} else {
			w.l("%s %s;", cidr, denied)
		}
	}
	w.l("default %s;", def)
	w.close()
}
