/**
 * Graphite chart runtime — a single, dependency-free SVG renderer for all
 * twelve Graphite chart types. Generated by Graphite; edit freely, it is your code.
 *
 * Relay: header, tooltip and SVG text restyled to match the design system
 * (Geist, 13/600 card titles, 30/600 stat values, mono axis labels, .chart-tip).
 */

import { useEffect, useId, useRef, useState, useSyncExternalStore } from "react";
import type { CSSProperties, FocusEvent, KeyboardEvent, MouseEvent, ReactNode } from "react";

export type ChartType =
  | "line"
  | "area"
  | "bar"
  | "stacked"
  | "donut"
  | "scatter"
  | "radar"
  | "heatmap"
  | "sparkline"
  | "funnel"
  | "gauge"
  | "treemap";

export type ChartMode = "light" | "dark" | "auto";
export type ChartSurface = "solid" | "glass" | "transparent";
export type ChartCurve = "smooth" | "linear" | "step";

export interface GraphiteModeTokens {
  readonly background: string;
  readonly surface: string;
  readonly border: string;
  readonly text: string;
  readonly muted: string;
  readonly grid: string;
  readonly track: string;
}

export interface GraphiteTheme {
  readonly defaultMode: ChartMode;
  readonly surface: ChartSurface;
  readonly modes: { readonly light: GraphiteModeTokens; readonly dark: GraphiteModeTokens };
  /** Series colors; the first four are used, cycling. */
  readonly palette: readonly string[];
  /** Font family name, loaded by your app (e.g. via next/font or a stylesheet). */
  readonly font: string;
  readonly radius: number;
  readonly stroke: number;
  /** Fill intensity, 0–1. */
  readonly fill: number;
  readonly curve: ChartCurve;
  readonly grid: boolean;
  readonly legend: boolean;
  readonly labels: boolean;
}

export interface ChartProps<Row extends object> {
  readonly type: ChartType;
  readonly theme: GraphiteTheme;
  readonly data: readonly Row[];
  /** Field holding the x value / label / axis / day. */
  readonly x: string;
  /** Numeric series fields (line, area, stacked, radar). */
  readonly series?: readonly string[];
  /** Single numeric field (bar, donut, scatter, funnel, gauge, treemap). */
  readonly value?: readonly string[];
  /** Field holding a number[] (sparkline, heatmap). */
  readonly values?: readonly string[];
  readonly mode?: ChartMode;
  readonly surface?: ChartSurface;
  readonly title?: string;
  /** Faint text after the title, e.g. the time window. */
  readonly subtitle?: string;
  /** Replaces the computed headline number; false hides it. */
  readonly headline?: string | false;
  readonly unit?: string;
  readonly onPointClick?: (datum: Row) => void;
  readonly formatValue?: (value: number) => string;
  /** Small helper text shown bottom-right while nothing is hovered. */
  readonly hint?: string;
  readonly className?: string;
  readonly style?: CSSProperties;
  readonly role?: string;
  readonly "aria-label"?: string;
}

/* ------------------------------------------------------------------ */
/* helpers                                                             */
/* ------------------------------------------------------------------ */

const W = 640;
const BASE = 250;
const PT = 12;
const IH = BASE - PT;

/** Numbers and axis labels use the app's mono face. */
const MONO = "var(--font-mono, ui-monospace, monospace)";

/**
 * Font size for text inside the 640-wide plot viewBox that stays `px` CSS pixels on screen:
 * the root sets --gr-k to its rendered width / 640, so text does not shrink or grow with the card.
 */
const fs = (px: number): CSSProperties => ({ fontSize: `calc(${px}px / var(--gr-k, 1))` });

const r1 = (v: number) => Math.round(v * 10) / 10;
const clamp = (v: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, v));
const num = (v: unknown): number => (typeof v === "number" && Number.isFinite(v) ? v : parseFloat(String(v)) || 0);
const numArr = (v: unknown): number[] => (Array.isArray(v) ? v.map(num) : []);
/** Map a 0–100 normalized value to a y coordinate in the 640×300 plot. */
const Y = (v: number) => PT + IH - (v / 100) * IH;
const color = (i: number) => `var(--s${(i % 4) + 1})`;

/** Rounded share; a non-zero slice never reads as 0%. */
function pctLabel(v: number): string {
  if (v > 0 && v < 1) return "<1%";
  return `${Math.round(v)}%`;
}

export function formatCompact(v: number): string {
  const a = Math.abs(v);
  if (a >= 1e6) return `${(v / 1e6).toFixed(1)}M`;
  if (a >= 1000) return `${(v / 1000).toFixed(1)}k`;
  return String(Math.round(v * 10) / 10);
}

function pathOf(pts: readonly (readonly [number, number])[], curve: ChartCurve): string {
  if (!pts.length) return "";
  const p0 = pts[0];
  if (curve === "linear") return "M" + pts.map((p) => `${r1(p[0])},${r1(p[1])}`).join("L");
  if (curve === "step") {
    let d = `M${r1(p0[0])},${r1(p0[1])}`;
    for (let i = 1; i < pts.length; i++) {
      const mx = (pts[i - 1][0] + pts[i][0]) / 2;
      d += `H${r1(mx)}V${r1(pts[i][1])}`;
    }
    return d + `H${r1(pts[pts.length - 1][0])}`;
  }
  // Catmull-Rom → cubic Bézier
  let d = `M${r1(p0[0])},${r1(p0[1])}`;
  for (let i = 0; i < pts.length - 1; i++) {
    const a = pts[i - 1] ?? pts[i];
    const b = pts[i];
    const c = pts[i + 1];
    const e = pts[i + 2] ?? c;
    d += `C${r1(b[0] + (c[0] - a[0]) / 6)},${r1(b[1] + (c[1] - a[1]) / 6)} ${r1(c[0] - (e[0] - b[0]) / 6)},${r1(c[1] - (e[1] - b[1]) / 6)} ${r1(c[0])},${r1(c[1])}`;
  }
  return d;
}

interface Rect {
  readonly i: number;
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

/** Squarified treemap layout (Bruls et al.). Returns one rect per input, in input order. */
function squarify(values: readonly number[], x: number, y: number, w: number, h: number): Rect[] {
  const total = values.reduce((a, b) => a + Math.max(0, b), 0);
  const scale = total > 0 ? (w * h) / total : 0;
  const items = values
    .map((v, i) => ({ i, a: total > 0 ? Math.max(0, v) * scale : (w * h) / values.length }))
    .sort((p, q) => q.a - p.a);
  const out: Rect[] = [];
  const worst = (row: { a: number }[], side: number) => {
    const s = row.reduce((acc, it) => acc + it.a, 0);
    const mx = Math.max(...row.map((it) => it.a));
    const mn = Math.min(...row.map((it) => it.a));
    if (mn <= 0 || s <= 0) return Infinity;
    return Math.max((side * side * mx) / (s * s), (s * s) / (side * side * mn));
  };
  let rest = items;
  let bx = x;
  let by = y;
  let bw = w;
  let bh = h;
  while (rest.length) {
    const side = Math.min(bw, bh);
    const row = [rest[0]];
    let k = 1;
    while (k < rest.length && worst([...row, rest[k]], side) <= worst(row, side)) row.push(rest[k++]);
    rest = rest.slice(k);
    const s = row.reduce((acc, it) => acc + it.a, 0);
    if (bw >= bh) {
      const cw = bh > 0 ? s / bh : 0;
      let yy = by;
      for (const it of row) {
        const hh = cw > 0 ? it.a / cw : 0;
        out.push({ i: it.i, x: bx, y: yy, w: cw, h: hh });
        yy += hh;
      }
      bx += cw;
      bw -= cw;
    } else {
      const rh = bw > 0 ? s / bw : 0;
      let xx = bx;
      for (const it of row) {
        const ww = rh > 0 ? it.a / rh : 0;
        out.push({ i: it.i, x: xx, y: by, w: ww, h: rh });
        xx += ww;
      }
      by += rh;
      bh -= rh;
    }
  }
  return out.sort((p, q) => p.i - q.i);
}

/* ------------------------------------------------------------------ */
/* color mode                                                          */
/* ------------------------------------------------------------------ */

function subscribeMode(cb: () => void) {
  const mq = window.matchMedia("(prefers-color-scheme: dark)");
  mq.addEventListener("change", cb);
  const mo = new MutationObserver(cb);
  mo.observe(document.documentElement, { attributes: true, attributeFilter: ["data-theme"] });
  return () => {
    mq.removeEventListener("change", cb);
    mo.disconnect();
  };
}

function readMode(): "light" | "dark" {
  const attr = document.documentElement.getAttribute("data-theme");
  if (attr === "light" || attr === "dark") return attr;
  return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
}

/** Resolves "auto" from `<html data-theme>`, falling back to prefers-color-scheme. */
export function useResolvedMode(mode: ChartMode): "light" | "dark" {
  const system = useSyncExternalStore(subscribeMode, readMode, () => "light" as const);
  return mode === "auto" ? system : mode;
}

/* ------------------------------------------------------------------ */
/* tooltip                                                             */
/* ------------------------------------------------------------------ */

interface TipRow {
  readonly name: string;
  readonly color: string;
  readonly v: string;
}

/** Tooltip anchored at a percentage position inside its (position:relative) parent. */
function Tip({ x, y, title, rows }: { x: number; y: number; title: string; rows: readonly TipRow[] }) {
  const shift = clamp(x, 12, 88);
  return (
    <div
      role="status"
      style={{
        position: "absolute",
        left: `${x}%`,
        top: `${y}%`,
        transform: `translate(-${shift}%, calc(-100% - 10px))`,
        pointerEvents: "none",
        zIndex: 2,
        background: "var(--ink)",
        color: "var(--card)",
        padding: "5px 8px",
        borderRadius: 6,
        fontFamily: "var(--font-mono, ui-monospace, monospace)",
        fontSize: 11,
        lineHeight: 1.5,
        whiteSpace: "nowrap",
      }}
    >
      <div style={{ opacity: 0.65 }}>{title}</div>
      {rows.map((t) => (
        <div key={t.name} style={{ display: "flex", alignItems: "center", gap: 14, justifyContent: "space-between" }}>
          <span style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <span style={{ width: 7, height: 7, borderRadius: 999, background: t.color }} />
            {t.name}
          </span>
          <span style={{ fontWeight: 500, fontVariantNumeric: "tabular-nums" }}>{t.v}</span>
        </div>
      ))}
    </div>
  );
}

/* ------------------------------------------------------------------ */
/* chart body builders                                                 */
/* ------------------------------------------------------------------ */

type Datum = Record<string, unknown>;

interface Ctx {
  readonly type: ChartType;
  readonly rows: readonly Datum[];
  readonly xs: readonly string[];
  readonly xKey: string;
  readonly keys: readonly string[];
  readonly theme: GraphiteTheme;
  readonly palette: readonly string[];
  readonly fmt: (v: number) => string;
  readonly unit: string;
  readonly hi: number | null;
  readonly hj: number | null;
  readonly setHi: (i: number | null, j?: number | null) => void;
  readonly ring: string;
  readonly uid: string;
  /** Rendered width / 640. */
  readonly k: number;
}

interface Body {
  /** Number of hoverable items (for keyboard stepping). */
  readonly count: number;
  readonly node: ReactNode;
}

/** Every `step`-th index plus the last, dropping the one before last when it would crowd it. */
function thinIndices(n: number, max: number): number[] {
  const step = Math.max(1, Math.ceil(n / max));
  const out: number[] = [];
  for (let i = 0; i < n; i += step) out.push(i);
  if (n && out[out.length - 1] !== n - 1) {
    if (out.length > 1 && n - 1 - out[out.length - 1] < step * 0.6) out.pop();
    out.push(n - 1);
  }
  return out;
}

const svgPoint = (e: MouseEvent<SVGSVGElement>): [number, number] => {
  const s = e.currentTarget;
  const rc = s.getBoundingClientRect();
  const vb = s.viewBox.baseVal;
  return [((e.clientX - rc.left) / rc.width) * vb.width, ((e.clientY - rc.top) / rc.height) * vb.height];
};

const plotSvgStyle: CSSProperties = { display: "block", width: "100%", height: "auto", overflow: "visible" };
const wrap: CSSProperties = { position: "relative" };

function YTicks({ max, show, fmt }: { max: number; show: boolean; fmt: (v: number) => string }) {
  return (
    <g opacity={show ? 1 : 0}>
      {[0, 25, 50, 75, 100].map((v) => (
        <g key={v}>
          <line x1={0} x2={W} y1={r1(Y(v))} y2={r1(Y(v))} stroke="var(--grid)" vectorEffect="non-scaling-stroke" />
          <text x={0} y={r1(Y(v) - 5)} style={fs(10.5)} fontFamily={MONO} fill="var(--mute)">
            {fmt((v / 92) * max)}
          </text>
        </g>
      ))}
    </g>
  );
}

function XLabels({ items }: { items: readonly { x: number; label: string; anchor: "start" | "middle" | "end" }[] }) {
  return (
    <>
      {items.map((m, i) => (
        <text key={i} x={r1(m.x)} y={290} style={fs(11)} fontFamily={MONO} textAnchor={m.anchor} fill="var(--mute)">
          {m.label}
        </text>
      ))}
    </>
  );
}

function lineArea(c: Ctx): Body {
  const { rows, xs, keys, theme, fmt, hi, setHi, ring, uid, unit } = c;
  const n = rows.length;
  const cols = keys.map((k) => rows.map((o) => num(o[k])));
  const max = Math.max(1, ...cols.flat());
  const X = (i: number) => (n <= 1 ? (i === 0 ? 0 : W) : (i * W) / (n - 1));
  const pts = cols.map((col) => {
    const p = col.map((v, i) => [X(i), Y((v / max) * 92)] as const);
    return p.length === 1 ? [p[0], [W, p[0][1]] as const] : p;
  });
  const fillTop = c.type === "line" ? theme.fill * 0.4 : theme.fill;
  const labelIdx = new Set(thinIndices(n, 8));
  const xIdx = thinIndices(n, 6);
  const onMove = (e: MouseEvent<SVGSVGElement>) => {
    const [vx, vy] = svgPoint(e);
    if (vy > 260 || n === 0) return;
    setHi(clamp(Math.round(vx / (W / Math.max(1, n - 1))), 0, n - 1));
  };
  const h = hi != null && hi < n ? hi : null;
  const tipY = h != null ? Math.min(...pts.map((p) => p[h][1])) : 0;
  return {
    count: n,
    node: (
      <div style={wrap}>
        <svg viewBox="0 0 640 300" style={plotSvgStyle} onMouseMove={onMove}>
          <defs>
            {keys.map((k, j) => (
              <linearGradient key={k} id={`${uid}g${j}`} x1="0" y1="0" x2="0" y2="1">
                <stop offset="0" stopColor={color(j)} stopOpacity={fillTop} />
                <stop offset="1" stopColor={color(j)} stopOpacity={0} />
              </linearGradient>
            ))}
          </defs>
          <YTicks max={max} show={theme.grid} fmt={fmt} />
          {pts
            .map((p, j) => {
              const d = pathOf(p, theme.curve);
              const area = `${d}L${r1(p[p.length - 1][0])},${BASE}L${r1(p[0][0])},${BASE}Z`;
              return (
                <g key={keys[j]}>
                  <path d={area} fill={`url(#${uid}g${j})`} />
                  <path d={d} fill="none" stroke={color(j)} strokeWidth={theme.stroke} strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" />
                </g>
              );
            })
            .reverse()}
          {h != null && (
            <line x1={r1(pts[0][h][0])} x2={r1(pts[0][h][0])} y1={0} y2={BASE} stroke="var(--ink)" strokeOpacity={0.25} strokeDasharray="2 4" vectorEffect="non-scaling-stroke" />
          )}
          {theme.labels &&
            pts[0] &&
            cols[0].map((v, i) =>
              labelIdx.has(i) ? (
                <g key={i}>
                  <circle cx={r1(pts[0][i][0])} cy={r1(pts[0][i][1])} r={3.5} fill="var(--s1)" stroke={ring} strokeWidth={2} />
                  <text
                    x={r1(pts[0][i][0])}
                    y={r1(pts[0][i][1] - 10)}
                    style={fs(10.5)}
                    fontWeight={500} fontFamily={MONO}
                    textAnchor={i === 0 ? "start" : i === n - 1 ? "end" : "middle"}
                    fill="var(--ink)"
                  >
                    {fmt(v)}
                  </text>
                </g>
              ) : null,
            )}
          {h != null &&
            pts
              .map((p, j) => (
                <circle key={j} cx={r1(p[h][0])} cy={r1(p[h][1])} r={5} fill={color(j)} stroke={ring} strokeWidth={3} />
              ))
              .reverse()}
          <XLabels
            items={xIdx.map((i) => ({ x: X(i), label: xs[i], anchor: i === 0 ? "start" : i === n - 1 ? "end" : "middle" }) as const)}
          />
        </svg>
        {h != null && (
          <Tip
            x={(pts[0][h][0] / W) * 100}
            y={(tipY / 300) * 100}
            title={xs[h]}
            rows={keys.map((k, j) => ({ name: k, color: c.palette[j % 4], v: fmt(cols[j][h]) + (unit ? ` ${unit}` : "") }))}
          />
        )}
      </div>
    ),
  };
}

function bar(c: Ctx): Body {
  const { rows, xs, keys, theme, fmt, hi, setHi } = c;
  const raw = rows.map((o) => Math.max(0, num(o[keys[0]])));
  const max = Math.max(1, ...raw);
  const n = raw.length;
  const slot = W / Math.max(1, n);
  const bw = slot * 0.56;
  const top = raw.indexOf(Math.max(...raw));
  const rx = Math.min(theme.radius, 14);
  const bars = raw.map((v, i) => {
    const x = i * slot + (slot - bw) / 2;
    const y = Y((v / max) * 92);
    return { x, y, cx: x + bw / 2 };
  });
  const onMove = (e: MouseEvent<SVGSVGElement>) => {
    const [vx, vy] = svgPoint(e);
    if (vy > 260 || !n) return;
    setHi(clamp(Math.floor(vx / slot), 0, n - 1));
  };
  const h = hi != null && hi < n ? hi : null;
  return {
    count: n,
    node: (
      <div style={wrap}>
        <svg viewBox="0 0 640 300" style={plotSvgStyle} onMouseMove={onMove}>
          <YTicks max={max} show={theme.grid} fmt={fmt} />
          {bars.map((b, i) => (
            <g key={i}>
              <rect x={r1(b.x)} y={0} width={r1(bw)} height={BASE} rx={rx} fill="var(--track)" />
              <rect
                x={r1(b.x)}
                y={r1(b.y)}
                width={r1(bw)}
                height={r1(BASE - b.y)}
                rx={rx}
                fill={i === top ? "var(--s1)" : `color-mix(in oklab, var(--s1) ${Math.round(35 + theme.fill * 50)}%, var(--track))`}
                opacity={h == null || h === i ? 1 : 0.45}
                style={{ transition: "opacity .15s" }}
              />
              {theme.labels && (
                <text x={r1(b.cx)} y={r1(b.y - 10)} style={fs(11)} fontWeight={500} fontFamily={MONO} textAnchor="middle" fill="var(--ink)">
                  {fmt(raw[i])}
                </text>
              )}
            </g>
          ))}
          <XLabels items={xs.map((label, i) => ({ x: i * slot + slot / 2, label, anchor: "middle" }) as const)} />
        </svg>
        {h != null && (
          <Tip x={(bars[h].cx / W) * 100} y={(bars[h].y / 300) * 100} title={xs[h]} rows={[{ name: keys[0], color: c.palette[0], v: fmt(raw[h]) }]} />
        )}
      </div>
    ),
  };
}

function stacked(c: Ctx): Body {
  const { rows, xs, keys, theme, fmt, hi, setHi } = c;
  const n = rows.length;
  const slot = W / Math.max(1, n);
  const sw = slot * 0.5;
  const totals = rows.map((o) => keys.reduce((a, k) => a + Math.max(0, num(o[k])), 0));
  const tmax = Math.max(1, ...totals);
  const rx = Math.min(theme.radius, 6);
  const onMove = (e: MouseEvent<SVGSVGElement>) => {
    const [vx, vy] = svgPoint(e);
    if (vy > 260 || !n) return;
    setHi(clamp(Math.floor(vx / slot), 0, n - 1));
  };
  const h = hi != null && hi < n ? hi : null;
  const totalY = (i: number) => Y((totals[i] / tmax) * 92) - 8;
  return {
    count: n,
    node: (
      <div style={wrap}>
        <svg viewBox="0 0 640 300" style={plotSvgStyle} onMouseMove={onMove}>
          <YTicks max={tmax} show={theme.grid} fmt={fmt} />
          {rows.map((o, i) => {
            let cum = 0;
            return (
              <g key={i} opacity={h == null || h === i ? 1 : 0.4} style={{ transition: "opacity .15s" }}>
                {keys.map((k, j) => {
                  const v = (Math.max(0, num(o[k])) / tmax) * 92;
                  const y0 = Y(cum);
                  const y1 = Y(cum + v);
                  cum += v;
                  return (
                    <rect
                      key={k}
                      x={r1(i * slot + (slot - sw) / 2)}
                      y={r1(y1 + 1)}
                      width={r1(sw)}
                      height={r1(Math.max(0, y0 - y1 - 2))}
                      rx={rx}
                      fill={color(j)}
                    />
                  );
                })}
              </g>
            );
          })}
          {theme.labels &&
            totals.map((t, i) => (
              <text key={i} x={r1(i * slot + slot / 2)} y={r1(totalY(i))} style={fs(11)} fontWeight={500} fontFamily={MONO} textAnchor="middle" fill="var(--ink)">
                {fmt(t)}
              </text>
            ))}
          <XLabels items={xs.map((label, i) => ({ x: i * slot + slot / 2, label, anchor: "middle" }) as const)} />
        </svg>
        {h != null && (
          <Tip
            x={((h * slot + slot / 2) / W) * 100}
            y={(totalY(h) / 300) * 100}
            title={`${xs[h]} · total ${fmt(totals[h])}`}
            rows={keys.map((k, j) => ({ name: k, color: c.palette[j % 4], v: fmt(num(rows[h][k])) }))}
          />
        )}
      </div>
    ),
  };
}

/** Least-squares fit and Pearson correlation. */
function regression(xs: readonly number[], ys: readonly number[]) {
  const n = xs.length;
  if (n < 2) return { slope: 0, intercept: ys[0] ?? 0, r: 0 };
  const mx = xs.reduce((a, b) => a + b, 0) / n;
  const my = ys.reduce((a, b) => a + b, 0) / n;
  let sxy = 0;
  let sxx = 0;
  let syy = 0;
  for (let i = 0; i < n; i++) {
    sxy += (xs[i] - mx) * (ys[i] - my);
    sxx += (xs[i] - mx) ** 2;
    syy += (ys[i] - my) ** 2;
  }
  const slope = sxx ? sxy / sxx : 0;
  return { slope, intercept: my - slope * mx, r: sxx && syy ? sxy / Math.sqrt(sxx * syy) : 0 };
}

function scatterPoints(rows: readonly Datum[], xKey: string, yKey: string) {
  const sx = rows.map((o) => num(o[xKey]));
  const sy = rows.map((o) => num(o[yKey]));
  return { sx, sy, sxm: Math.max(1, ...sx), sym: Math.max(1, ...sy) };
}

function scatter(c: Ctx): Body {
  const { rows, xKey, keys, theme, fmt, hi, setHi, ring } = c;
  const { sx, sy, sxm, sym } = scatterPoints(rows, xKey, keys[0]);
  const px = (v: number) => 20 + (v / sxm) * 600;
  const py = (v: number) => Y((v / sym) * 92);
  const pts = sx.map((v, i) => ({ x: px(v), y: py(sy[i]), halo: 6 + (((i + 1) * 9301 + 49297) % 233280) / 23328 }));
  const fit = regression(sx, sy);
  const n = pts.length;
  const onMove = (e: MouseEvent<SVGSVGElement>) => {
    const [vx, vy] = svgPoint(e);
    if (vy > 260 || !n) return;
    let best = 0;
    let bd = Infinity;
    pts.forEach((p, i) => {
      const d = (p.x - vx) ** 2 + (p.y - vy) ** 2;
      if (d < bd) {
        bd = d;
        best = i;
      }
    });
    setHi(best);
  };
  const h = hi != null && hi < n ? hi : null;
  const labelEvery = Math.max(1, Math.ceil(n / 8));
  return {
    count: n,
    node: (
      <div style={wrap}>
        <svg viewBox="0 0 640 300" style={plotSvgStyle} onMouseMove={onMove}>
          <YTicks max={sym} show={theme.grid} fmt={fmt} />
          {n >= 2 && (
            <line
              x1={r1(px(0))}
              y1={r1(clamp(py(fit.intercept), 0, BASE))}
              x2={r1(px(sxm))}
              y2={r1(clamp(py(fit.intercept + fit.slope * sxm), 0, BASE))}
              stroke="var(--s1)"
              strokeWidth={1.5}
              strokeDasharray="4 5"
              strokeOpacity={0.7}
            />
          )}
          {pts.map((p, i) => (
            <g key={i}>
              <circle cx={r1(p.x)} cy={r1(p.y)} r={r1(p.halo)} fill={`var(--s${(i % 3) + 1})`} fillOpacity={0.22} />
              <circle
                cx={r1(p.x)}
                cy={r1(p.y)}
                r={h === i ? 6 : 3.5}
                fill={`var(--s${(i % 3) + 1})`}
                stroke={ring}
                strokeWidth={h === i ? 2.5 : 0}
              />
            </g>
          ))}
          {theme.labels &&
            pts.map((p, i) =>
              i % labelEvery === 0 ? (
                <text key={i} x={r1(p.x)} y={r1(p.y - 9)} fontSize={10} fontWeight={600} textAnchor="middle" fill="var(--mute)">
                  {fmt(sy[i])}
                </text>
              ) : null,
            )}
          <XLabels
            items={[
              { x: 0, label: fmt(0), anchor: "start" },
              { x: W, label: fmt(sxm), anchor: "end" },
            ]}
          />
        </svg>
        {h != null && (
          <Tip
            x={(pts[h].x / W) * 100}
            y={(pts[h].y / 300) * 100}
            title={`${xKey} ${fmt(sx[h])}`}
            rows={[{ name: keys[0], color: c.palette[h % 3], v: fmt(sy[h]) }]}
          />
        )}
      </div>
    ),
  };
}

function heatGeometry(rows: readonly Datum[], key: string) {
  const hRows = rows.slice(0, 12);
  const grid = hRows.map((o) => numArr(o[key]));
  const cols = clamp(Math.max(1, ...grid.map((g) => g.length)), 1, 48);
  const nr = Math.max(1, hRows.length);
  return { hRows, grid, cols, cw: (W - 40) / cols, chh: BASE / nr, max: Math.max(1, ...grid.flat()) };
}

function heatmap(c: Ctx): Body {
  const { rows, keys, theme, fmt, hi, hj, setHi, xKey } = c;
  const { hRows, grid, cols, cw, chh, max } = heatGeometry(rows, keys[0]);
  const rx = Math.min(theme.radius, 6);
  const hourly = cols === 24;
  const colLabel = (h: number) => (hourly ? `${h}:00` : String(h));
  const onMove = (e: MouseEvent<SVGSVGElement>) => {
    const [vx, vy] = svgPoint(e);
    const d = Math.floor(vy / chh);
    const hh = Math.floor((vx - 40) / cw);
    if (d >= 0 && d < hRows.length && hh >= 0 && hh < cols) setHi(d, hh);
  };
  const tickCols = hourly ? [0, 6, 12, 18, 23] : Array.from(new Set([0, 1, 2, 3, 4].map((k) => Math.round((k * (cols - 1)) / 4))));
  const showText = theme.labels && cw >= 14;
  const active = hi != null && hj != null && hi < hRows.length && hj < cols;
  return {
    count: hRows.length,
    node: (
      <div style={wrap}>
        <svg viewBox="0 0 640 300" style={plotSvgStyle} onMouseMove={onMove}>
          {grid.map((arr, d) =>
            Array.from({ length: cols }, (_, h) => {
              const v = num(arr[h]);
              const o = v / max;
              const x = 40 + h * cw + 1.5;
              const y = d * chh + 1.5;
              return (
                <g key={`${d}-${h}`}>
                  <rect x={r1(x)} y={r1(y)} width={r1(cw - 3)} height={r1(chh - 3)} rx={rx} fill="var(--track)" />
                  <rect
                    x={r1(x)}
                    y={r1(y)}
                    width={r1(cw - 3)}
                    height={r1(chh - 3)}
                    rx={rx}
                    fill="var(--s1)"
                    fillOpacity={r1(o * 100) / 100}
                    stroke={active && hi === d && hj === h ? "var(--ink)" : "none"}
                    strokeWidth={1.5}
                  />
                  {showText && (
                    <text
                      x={r1(40 + h * cw + cw / 2)}
                      y={r1(d * chh + chh / 2 + 3)}
                      fontSize={7.5}
                      fontWeight={600}
                      textAnchor="middle"
                      fill={o > 0.55 ? "#fff" : "var(--mute)"}
                    >
                      {fmt(v)}
                    </text>
                  )}
                </g>
              );
            }),
          )}
          {hRows.map((o, i) => (
            <text key={i} x={28} y={r1(i * chh + chh / 2 + 4)} fontSize={10} fontWeight={500} textAnchor="end" fill="var(--mute)">
              {String(o[xKey] ?? "")}
            </text>
          ))}
          <XLabels items={tickCols.map((h) => ({ x: 40 + h * cw + cw / 2, label: colLabel(h), anchor: "middle" }) as const)} />
        </svg>
        {active && (
          <Tip
            x={((40 + hj * cw + cw / 2) / W) * 100}
            y={((hi * chh) / 300) * 100}
            title={`${String(hRows[hi][xKey] ?? "")} · ${colLabel(hj)}`}
            rows={[{ name: keys[0], color: c.palette[0], v: fmt(num(grid[hi][hj])) }]}
          />
        )}
      </div>
    ),
  };
}

function donut(c: Ctx): Body {
  const { rows, xs, keys, theme, fmt, hi, setHi, k } = c;
  // Under ~300px the legend goes below the ring.
  const stack = k * W < 300;
  const raw = rows.slice(0, 8).map((o) => Math.max(0, num(o[keys[0]])));
  const sum = Math.max(1e-9, raw.reduce((a, b) => a + b, 0));
  const pct = raw.map((v) => (v / sum) * 100);
  const C = 2 * Math.PI * 86;
  const n = raw.length;
  const h = hi != null && hi < n ? hi : null;
  const cap = theme.radius > 6 ? "round" : "butt";
  let acc = 0;
  const slices = pct.map((v) => {
    const s = { v, off: (-acc * C) / 100 };
    acc += v;
    return s;
  });
  const onMove = (e: MouseEvent<SVGSVGElement>) => {
    const [vx, vy] = svgPoint(e);
    const a = ((Math.atan2(vy - 110, vx - 110) * 180) / Math.PI + 90 + 360) % 360;
    let run = 0;
    for (let i = 0; i < n; i++) {
      run += pct[i] * 3.6;
      if (a <= run) {
        setHi(i);
        return;
      }
    }
  };
  const center = h ?? 0;
  return {
    count: n,
    node: (
      <div style={{ display: "grid", gridTemplateColumns: stack ? "minmax(0, 1fr)" : "minmax(96px, 140px) minmax(0, 1fr)", gap: stack ? 14 : 20, alignItems: "center" }}>
        <div style={{ ...wrap, width: "100%", maxWidth: 160, justifySelf: "center" }}>
          <svg viewBox="0 0 220 220" style={{ display: "block", width: "100%", height: "auto", overflow: "visible" }} onMouseMove={onMove}>
            <g transform="rotate(-90 110 110)">
              {slices.map((s, i) => (
                <circle
                  key={i}
                  cx={110}
                  cy={110}
                  r={86}
                  fill="none"
                  stroke={color(i)}
                  strokeWidth={18 + theme.stroke * 3 + (h === i ? 6 : 0)}
                  strokeLinecap={cap}
                  strokeDasharray={`${r1(Math.max(0, (C * s.v) / 100 - 6))} ${r1(C - (C * s.v) / 100 + 6)}`}
                  strokeDashoffset={r1(s.off)}
                  opacity={h == null || h === i ? 1 : 0.35}
                  style={{ transition: "opacity .15s, stroke-width .15s" }}
                />
              ))}
            </g>
            <text x={110} y={106} textAnchor="middle" fontSize={30} fontWeight={600} letterSpacing={-0.6} fill="var(--ink)">
              {n ? pctLabel(pct[center]) : ""}
            </text>
            <text x={110} y={130} textAnchor="middle" fontSize={12} fontFamily={MONO} fill="var(--mute)">
              {xs[center] ?? ""}
            </text>
          </svg>
          {h != null && (
            <Tip x={50} y={4} title={xs[h]} rows={[{ name: keys[0], color: c.palette[h % 4], v: `${fmt(raw[h])} · ${pctLabel(pct[h])}` }]} />
          )}
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: 7, fontSize: 12, minWidth: 0, maxWidth: 320 }}>
          {raw.map((_, i) => (
            <div
              key={i}
              onMouseEnter={() => setHi(i)}
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                gap: 8,
                padding: "0 6px 7px",
                margin: "0 -6px",
                borderBottom: "1px solid var(--grid)",
                opacity: h == null || h === i ? 1 : 0.35,
                cursor: "pointer",
                transition: "opacity .15s",
              }}
            >
              <span style={{ display: "flex", alignItems: "center", gap: 8, color: "var(--mute)", minWidth: 0, whiteSpace: "nowrap" }}>
                <span style={{ flex: "none", width: 8, height: 8, borderRadius: 2, background: color(i) }} />
                <span style={{ overflow: "hidden", textOverflow: "ellipsis" }}>{xs[i]}</span>
              </span>
              <span style={{ flex: "none", whiteSpace: "nowrap", fontVariantNumeric: "tabular-nums", fontFamily: MONO, fontSize: 12 }}>
                {pctLabel(pct[i])}
              </span>
            </div>
          ))}
        </div>
      </div>
    ),
  };
}

function radar(c: Ctx): Body {
  const { rows, xs, keys, theme, fmt, hi, setHi, ring } = c;
  const n = clamp(rows.length, 3, 12);
  const cx = 320;
  const cy = 150;
  const R = 118;
  const ang = (i: number) => -Math.PI / 2 + (i * 2 * Math.PI) / n;
  const pt = (i: number, f: number) => [cx + Math.cos(ang(i)) * R * f, cy + Math.sin(ang(i)) * R * f] as const;
  const poly = (fs: readonly number[]) => fs.map((f, i) => pt(i, f).map(r1).join(",")).join(" ");
  const max = Math.max(1, ...keys.flatMap((k) => rows.slice(0, n).map((o) => num(o[k]))));
  const frac = keys.map((k) => Array.from({ length: n }, (_, i) => (rows[i] ? clamp(num(rows[i][k]) / max, 0, 1) : 0)));
  const count = Math.min(rows.length, n);
  const onMove = (e: MouseEvent<SVGSVGElement>) => {
    const [vx, vy] = svgPoint(e);
    const a = ((Math.atan2(vy - cy, vx - cx) * 180) / Math.PI + 90 + 180 / n + 360) % 360;
    const i = Math.floor(a / (360 / n));
    if (i < count) setHi(i);
  };
  const h = hi != null && hi < count ? hi : null;
  return {
    count,
    node: (
      <div style={wrap}>
        <svg viewBox="0 0 640 300" style={plotSvgStyle} onMouseMove={onMove}>
          {[0.25, 0.5, 0.75, 1].map((f) => (
            <polygon key={f} points={poly(Array(n).fill(f))} fill="none" stroke="var(--grid)" strokeLinejoin="round" opacity={theme.grid ? 1 : 0} />
          ))}
          {Array.from({ length: n }, (_, i) => {
            const [x, y] = pt(i, 1);
            const co = Math.cos(ang(i));
            return (
              <g key={i}>
                <line x1={cx} y1={cy} x2={r1(x)} y2={r1(y)} stroke="var(--grid)" opacity={theme.grid ? 1 : 0} />
                <text
                  x={r1(cx + co * (R + 18))}
                  y={r1(cy + Math.sin(ang(i)) * (R + 18) + 4)}
                  fontSize={11}
                  fontWeight={h === i ? 800 : 600}
                  textAnchor={Math.abs(co) < 0.1 ? "middle" : co > 0 ? "start" : "end"}
                  fill={h === i ? "var(--ink)" : "var(--mute)"}
                >
                  {xs[i] ?? ""}
                </text>
              </g>
            );
          })}
          {frac
            .map((fs, j) => (
              <polygon
                key={keys[j]}
                points={poly(fs)}
                fill={color(j)}
                fillOpacity={r1(theme.fill * 40) / 100}
                stroke={color(j)}
                strokeWidth={theme.stroke}
                strokeLinejoin="round"
              />
            ))
            .reverse()}
          {frac[0]?.slice(0, count).map((f, i) => {
            const [x, y] = pt(i, f);
            return (
              <g key={i}>
                <circle cx={r1(x)} cy={r1(y)} r={h === i ? 6.5 : 4} fill="var(--s1)" stroke={ring} strokeWidth={2} />
                {theme.labels && (
                  <text x={r1(x)} y={r1(y - 9)} fontSize={10.5} fontWeight={500} fontFamily={MONO} textAnchor="middle" fill="var(--ink)">
                    {fmt(num(rows[i][keys[0]]))}
                  </text>
                )}
              </g>
            );
          })}
        </svg>
        {h != null && (
          <Tip
            x={(pt(h, frac[0][h])[0] / W) * 100}
            y={((pt(h, frac[0][h])[1] - 4) / 300) * 100}
            title={xs[h]}
            rows={keys.map((k, j) => ({ name: k, color: c.palette[j % 4], v: fmt(num(rows[h][k])) }))}
          />
        )}
      </div>
    ),
  };
}

function sparkRow(values: readonly number[]) {
  const raw = values.length >= 2 ? values : [values[0] ?? 0, values[0] ?? 0];
  const n = raw.length;
  const max = Math.max(1, ...raw);
  const pts = raw.map((y, j) => [(j * 200) / (n - 1), 28 - (y / max) * 24] as const);
  const d = raw[n - 1] - raw[0];
  return { raw, pts, d, last: raw[n - 1], delta: `${d >= 0 ? "+" : ""}${raw[0] ? ((d / raw[0]) * 100).toFixed(1) : "0.0"}%` };
}

function sparkline(c: Ctx): Body {
  const { rows, xs, keys, theme, fmt, hi, setHi } = c;
  const lines = rows.map((o) => sparkRow(numArr(o[keys[0]])));
  const h = hi != null && hi < lines.length ? hi : null;
  return {
    count: lines.length,
    node: (
      <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
        {lines.map((s, i) => (
          <div
            key={i}
            onMouseEnter={() => setHi(i)}
            style={{
              position: "relative",
              display: "grid",
              gridTemplateColumns: "minmax(64px, 120px) minmax(0, 1fr) minmax(56px, 90px) minmax(52px, 70px)",
              gap: 16,
              alignItems: "center",
              padding: "12px 14px",
              borderRadius: "calc(var(--rad) * .6)",
              background: h === i ? "color-mix(in oklab, var(--s1) 12%, var(--track))" : "var(--track)",
              outline: `1px solid ${h === i ? "var(--s1)" : "transparent"}`,
              fontSize: 13,
              fontWeight: 600,
              transition: "background .15s",
            }}
          >
            <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{xs[i]}</span>
            <svg viewBox="0 0 200 32" width="100%" height={32} preserveAspectRatio="none" style={{ display: "block", overflow: "visible" }}>
              <path
                d={pathOf(s.pts, theme.curve)}
                fill="none"
                stroke={s.d >= 0 ? "var(--s2)" : "var(--s3)"}
                strokeWidth={theme.stroke}
                strokeLinecap="round"
                vectorEffect="non-scaling-stroke"
              />
            </svg>
            <span style={{ textAlign: "right", fontVariantNumeric: "tabular-nums" }}>{fmt(s.last)}</span>
            <span style={{ textAlign: "right", fontSize: 12, color: s.d >= 0 ? "var(--s2)" : "var(--s3)" }}>{s.delta}</span>
            {h === i && (
              <Tip
                x={50}
                y={8}
                title={xs[i]}
                rows={[
                  { name: "latest", color: c.palette[1 % c.palette.length], v: fmt(s.last) },
                  { name: "min / max", color: c.palette[3 % c.palette.length], v: `${fmt(Math.min(...s.raw))} / ${fmt(Math.max(...s.raw))}` },
                ]}
              />
            )}
          </div>
        ))}
      </div>
    ),
  };
}

function funnel(c: Ctx): Body {
  const { rows, xs, keys, theme, fmt, hi, setHi } = c;
  const raw = rows.slice(0, 8).map((o) => Math.max(0, num(o[keys[0]])));
  const n = raw.length;
  const max = Math.max(1, ...raw);
  const H = Math.max(40, n * 52 - 12);
  const rx = Math.min(theme.radius, 12);
  const onMove = (e: MouseEvent<SVGSVGElement>) => {
    const [, vy] = svgPoint(e);
    const i = Math.floor(vy / 52);
    if (i >= 0 && i < n) setHi(i);
  };
  const h = hi != null && hi < n ? hi : null;
  const opacity = (i: number) => Math.max(0.2, 1 - i * 0.16);
  return {
    count: n,
    node: (
      <div style={wrap}>
        <svg viewBox={`0 0 640 ${H}`} style={plotSvgStyle} onMouseMove={onMove}>
          {raw.map((v, i) => {
            const w = (W * v) / max;
            return (
              <g key={i}>
                <rect x={0} y={i * 52} width={W} height={40} rx={rx} fill="var(--track)" />
                <rect
                  x={0}
                  y={i * 52}
                  width={r1(w)}
                  height={40}
                  rx={rx}
                  fill="var(--s1)"
                  fillOpacity={opacity(i)}
                  stroke={h === i ? "var(--ink)" : "none"}
                  strokeWidth={2}
                />
                <text x={16} y={i * 52 + 25} fontSize={12} fontWeight={600} fill={opacity(i) > 0.55 && w > 120 ? "#fff" : "var(--ink)"}>
                  {xs[i]}
                </text>
                <text x={624} y={i * 52 + 25} fontSize={12} fontWeight={500} fontFamily={MONO} textAnchor="end" fill="var(--ink)">
                  {fmt(v)}
                </text>
              </g>
            );
          })}
        </svg>
        {h != null && (
          <Tip
            x={(((W * raw[h]) / max / 2) / W) * 100}
            y={((h * 52) / H) * 100}
            title={xs[h]}
            rows={[
              { name: keys[0], color: c.palette[0], v: fmt(raw[h]) },
              { name: "share", color: c.palette[1 % c.palette.length], v: h ? `${Math.round((raw[h] / (raw[0] || 1)) * 100)}% of top` : "100%" },
            ]}
          />
        )}
      </div>
    ),
  };
}

function gaugeValue(rows: readonly Datum[], key: string) {
  return clamp(Math.round(num(rows[0]?.[key])), 0, 100);
}

function gauge(c: Ctx): Body {
  const { rows, xs, keys, theme, unit, ring, uid } = c;
  const L = Math.PI * 200;
  const gv = gaugeValue(rows, keys[0]);
  const ga = Math.PI * (1 - gv / 100);
  const cap = theme.radius > 6 ? "round" : "butt";
  const sw = 20 + theme.stroke * 4;
  return {
    count: rows.length ? 1 : 0,
    node: (
      <svg viewBox="0 0 640 300" style={plotSvgStyle}>
        <defs>
          <linearGradient id={`${uid}gauge`} x1="0" y1="0" x2="1" y2="0">
            <stop offset="0" stopColor="var(--s2)" />
            <stop offset="1" stopColor="var(--s1)" />
          </linearGradient>
        </defs>
        <path d="M 120 250 A 200 200 0 0 1 520 250" fill="none" stroke="var(--track)" strokeWidth={sw} strokeLinecap={cap} />
        <path
          d="M 120 250 A 200 200 0 0 1 520 250"
          fill="none"
          stroke={`url(#${uid}gauge)`}
          strokeWidth={sw}
          strokeLinecap={cap}
          strokeDasharray={`${r1((L * gv) / 100)} ${r1(L)}`}
        />
        <circle cx={r1(320 + Math.cos(ga) * 200)} cy={r1(250 - Math.sin(ga) * 200)} r={10} fill={ring} stroke="var(--s1)" strokeWidth={4} />
        <text x={320} y={225} textAnchor="middle" fontSize={76} fontWeight={800} letterSpacing={-4} fill="var(--ink)">
          {gv}
        </text>
        <text x={320} y={255} textAnchor="middle" fontSize={13} fontWeight={600} fill="var(--mute)">
          {[xs[0], unit].filter(Boolean).join(" · ")}
        </text>
        <text x={120} y={285} textAnchor="middle" fontSize={11} fontWeight={500} fill="var(--mute)">
          0
        </text>
        <text x={520} y={285} textAnchor="middle" fontSize={11} fontWeight={500} fill="var(--mute)">
          100
        </text>
      </svg>
    ),
  };
}

function treemap(c: Ctx): Body {
  const { rows, xs, keys, theme, fmt, hi, setHi } = c;
  const raw = rows.slice(0, 12).map((o) => Math.max(0, num(o[keys[0]])));
  const max = Math.max(1, ...raw);
  const rects = squarify(raw, 0, 0, W, 300);
  const rx = Math.min(theme.radius, 14);
  const onMove = (e: MouseEvent<SVGSVGElement>) => {
    const [vx, vy] = svgPoint(e);
    const hit = rects.find((n) => vx >= n.x && vx <= n.x + n.w && vy >= n.y && vy <= n.y + n.h);
    if (hit) setHi(hit.i);
  };
  const h = hi != null && hi < rects.length ? hi : null;
  return {
    count: rects.length,
    node: (
      <div style={wrap}>
        <svg viewBox="0 0 640 300" style={plotSvgStyle} onMouseMove={onMove}>
          {rects.map((n) => {
            const o = Math.max(0.3, raw[n.i] / max);
            const w = Math.max(0, n.w - 4);
            const hh = Math.max(0, n.h - 4);
            const tc = o > 0.6 ? "#fff" : "var(--ink)";
            return (
              <g key={n.i}>
                <rect
                  x={r1(n.x + 2)}
                  y={r1(n.y + 2)}
                  width={r1(w)}
                  height={r1(hh)}
                  rx={Math.min(rx, w / 2, hh / 2)}
                  fill={color(n.i)}
                  fillOpacity={r1(o * 100) / 100}
                  stroke={h === n.i ? "var(--ink)" : "none"}
                  strokeWidth={2}
                />
                {w > 56 && hh > 34 && (
                  <text x={r1(n.x + 14)} y={r1(n.y + 24)} fontSize={12} fontWeight={500} fontFamily={MONO} fill={tc}>
                    {xs[n.i]}
                  </text>
                )}
                {w > 56 && hh > 52 && (
                  <text x={r1(n.x + 14)} y={r1(n.y + 42)} fontSize={11} fontWeight={500} fill={tc} opacity={0.7}>
                    {fmt(raw[n.i])}
                  </text>
                )}
              </g>
            );
          })}
        </svg>
        {h != null && (
          <Tip
            x={((rects[h].x + rects[h].w / 2) / W) * 100}
            y={((rects[h].y + 12) / 300) * 100}
            title={xs[h]}
            rows={[{ name: keys[0], color: c.palette[h % 4], v: fmt(raw[h]) }]}
          />
        )}
      </div>
    ),
  };
}

const BUILDERS: Record<ChartType, (c: Ctx) => Body> = {
  line: lineArea,
  area: lineArea,
  bar,
  stacked,
  donut,
  scatter,
  radar,
  heatmap,
  sparkline,
  funnel,
  gauge,
  treemap,
};

/** The headline number shown above the chart. */
function headline(type: ChartType, rows: readonly Datum[], xKey: string, keys: readonly string[], fmt: (v: number) => string): string {
  const k = keys[0];
  const col = rows.map((o) => num(o[k]));
  const sum = (a: readonly number[]) => a.reduce((x, y) => x + y, 0);
  switch (type) {
    case "gauge":
      return String(gaugeValue(rows, k));
    case "line":
    case "area":
      return fmt(col[col.length - 1] ?? 0);
    case "sparkline": {
      const first = numArr(rows[0]?.[k]);
      return fmt(first[first.length - 1] ?? 0);
    }
    case "scatter": {
      const { sx, sy } = scatterPoints(rows, xKey, k);
      return `r = ${regression(sx, sy).r.toFixed(2)}`;
    }
    case "radar":
      return fmt(Math.round(sum(col) / Math.max(1, col.length)));
    case "stacked":
      return fmt(sum(rows.map((o) => sum(keys.map((key) => num(o[key]))))));
    case "heatmap":
      return fmt(sum(rows.flatMap((o) => numArr(o[k]))));
    default:
      return fmt(sum(col));
  }
}

/* ------------------------------------------------------------------ */
/* Chart                                                               */
/* ------------------------------------------------------------------ */

function ChartRoot<Row extends object>(props: ChartProps<Row>) {
  const { type, theme, data, x, title = "", subtitle, unit = "", onPointClick, formatValue, hint, className, style } = props;
  const resolved = useResolvedMode(props.mode ?? theme.defaultMode);
  const surface = props.surface ?? theme.surface;
  const tokens = theme.modes[resolved];
  const dark = resolved === "dark";
  const uid = `gr${useId().replace(/[^a-zA-Z0-9]/g, "")}`;
  const [hover, setHover] = useState<{ i: number | null; j: number | null }>({ i: null, j: null });
  const [focusRing, setFocusRing] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);
  const [k, setK] = useState(1);

  useEffect(() => {
    const el = rootRef.current;
    if (!el || typeof ResizeObserver === "undefined") return;
    const ro = new ResizeObserver(([entry]) => {
      const w = entry.contentRect.width;
      if (w > 0) setK(Math.round((w / W) * 1000) / 1000);
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, []);

  const rows = data as unknown as readonly Datum[];
  const keys = (props.series ?? props.value ?? props.values ?? []).filter(Boolean);
  const safeKeys = keys.length ? keys : ["value"];
  const palette = theme.palette.length ? theme.palette : ["#8b7cff"];
  const fmt = formatValue ?? formatCompact;
  const xs = rows.map((o) => String(o[x] ?? ""));

  const setHi = (i: number | null, j: number | null = null) => {
    if (i !== hover.i || j !== hover.j) setHover({ i, j });
  };

  const ring = surface === "solid" ? "var(--card)" : dark ? "#151821" : "#ffffff";
  const ctx: Ctx = { type, rows, xs, xKey: x, keys: safeKeys, theme, palette, fmt, unit, hi: hover.i, hj: hover.j, setHi, ring, uid, k };
  const body = rows.length ? BUILDERS[type](ctx) : { count: 0, node: <EmptyPlot /> };
  const count = body.count;

  const onKey = (e: KeyboardEvent<HTMLDivElement>) => {
    if (e.key === "Escape") return setHi(null);
    if (e.key === "Enter" && hover.i != null && data[hover.i] && onPointClick) return onPointClick(data[hover.i]);
    const horizontal = e.key === "ArrowRight" ? 1 : e.key === "ArrowLeft" ? -1 : 0;
    const vertical = e.key === "ArrowDown" ? 1 : e.key === "ArrowUp" ? -1 : 0;
    if ((!horizontal && !vertical) || !count) return;
    e.preventDefault();
    if (type === "heatmap") {
      const cols = heatGeometry(rows, safeKeys[0]).cols;
      const i = vertical ? ((hover.i ?? -1) + vertical + count) % count : (hover.i ?? 0);
      const j = horizontal ? ((hover.j ?? -1) + horizontal + cols) % cols : (hover.j ?? 0);
      return setHi(i, j);
    }
    setHi(((hover.i ?? -1) + (horizontal || vertical) + count) % count);
  };

  const surfaces: Record<ChartSurface, CSSProperties> = {
    solid: { background: "var(--card)", border: "1px solid var(--bd)", boxShadow: "0 30px 80px -30px rgba(0,0,0,.35)" },
    glass: {
      background: dark
        ? "linear-gradient(135deg, rgba(255,255,255,.10), rgba(255,255,255,.03))"
        : "linear-gradient(135deg, rgba(255,255,255,.65), rgba(255,255,255,.30))",
      border: dark ? "1px solid rgba(255,255,255,.16)" : "1px solid rgba(255,255,255,.75)",
      backdropFilter: "blur(22px) saturate(1.4)",
      WebkitBackdropFilter: "blur(22px) saturate(1.4)",
      boxShadow: dark
        ? "0 30px 80px -30px rgba(0,0,0,.6), inset 0 1px 0 rgba(255,255,255,.18)"
        : "0 30px 80px -30px rgba(40,50,90,.28), inset 0 1px 0 rgba(255,255,255,.9)",
    },
    transparent: { background: "transparent", border: "1px solid transparent", boxShadow: "none" },
  };

  const vars = {
    "--s1": palette[0],
    "--s2": palette[1 % palette.length],
    "--s3": palette[2 % palette.length],
    "--s4": palette[3 % palette.length],
    "--card": tokens.surface,
    "--bd": tokens.border,
    "--ink": tokens.text,
    "--mute": tokens.muted,
    "--grid": tokens.grid,
    "--track": tokens.track,
    "--rad": `${theme.radius}px`,
    "--gr-k": k,
  } as CSSProperties;

  const generic = /mono/i.test(theme.font) ? "ui-monospace, monospace" : "system-ui, sans-serif";
  const onFocus = (e: FocusEvent<HTMLDivElement>) => setFocusRing(e.currentTarget.matches(":focus-visible"));

  return (
    <div
      ref={rootRef}
      className={["graphite-chart", className].filter(Boolean).join(" ")}
      role={props.role}
      aria-label={props["aria-label"]}
      tabIndex={0}
      onKeyDown={onKey}
      onMouseLeave={() => setHi(null)}
      onFocus={onFocus}
      onBlur={() => setFocusRing(false)}
      onClick={() => hover.i != null && data[hover.i] && onPointClick?.(data[hover.i])}
      style={{
        ...vars,
        position: "relative",
        outline: "none",
        width: "100%",
        boxSizing: "border-box",
        borderRadius: "var(--rad)",
        padding: surface === "transparent" ? 0 : 20,
        display: "flex",
        flexDirection: "column",
        gap: 14,
        fontFamily: `'${theme.font}', ${generic}`,
        color: "var(--ink)",
        cursor: onPointClick ? "pointer" : "crosshair",
        transition: "background .2s, color .2s, box-shadow .2s",
        ...surfaces[surface],
        ...(focusRing ? { boxShadow: `0 0 0 2px color-mix(in oklab, var(--s1) 60%, transparent), ${surfaces[surface].boxShadow}` } : null),
        ...style,
      }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, flexWrap: "wrap" }}>
        <div>
          <div style={{ fontSize: 13, fontWeight: 600, color: "var(--ink)" }}>
            {title}
            {subtitle && <span style={{ fontWeight: 400, fontSize: 12, color: "var(--mute)" }}> · {subtitle}</span>}
          </div>
          {props.headline !== false && (
            <div style={{ fontSize: 30, fontWeight: 600, lineHeight: 1.1, letterSpacing: "-.02em", fontVariantNumeric: "tabular-nums", marginTop: 8 }}>
              {props.headline ?? headline(type, rows, x, safeKeys, fmt)}{" "}
              <span style={{ fontFamily: MONO, fontSize: 12, fontWeight: 400, letterSpacing: 0, color: "var(--mute)" }}>{type === "scatter" ? "" : unit}</span>
            </div>
          )}
        </div>
        {theme.legend && (
          <div style={{ display: "flex", gap: 12, flexWrap: "wrap", justifyContent: "flex-end", fontSize: 11, color: "var(--mute)" }}>
            {safeKeys.map((name, i) => (
              <span key={name} style={{ display: "flex", alignItems: "center", gap: 6 }}>
                <span style={{ width: 8, height: 8, borderRadius: 2, background: color(i) }} />
                {name}
              </span>
            ))}
          </div>
        )}
      </div>
      {body.node}
      {hint && (
        <div
          aria-hidden
          style={{
            position: "absolute",
            right: 26,
            bottom: 8,
            fontSize: 10,
            color: "var(--mute)",
            whiteSpace: "nowrap",
            opacity: hover.i == null ? 0.7 : 0,
            transition: "opacity .15s",
            pointerEvents: "none",
          }}
        >
          {hint}
        </div>
      )}
    </div>
  );
}

function EmptyPlot() {
  return (
    <div style={{ height: 200, display: "flex", alignItems: "center", justifyContent: "center", color: "var(--mute)", fontSize: 12 }}>
      No data in this range
    </div>
  );
}

/** Placeholder shown while rows load. Neutral colors so it works before a theme resolves. */
function ChartSkeleton({ className, ...rest }: { className?: string; "aria-busy"?: boolean }) {
  const bar = (w: string, h: number): CSSProperties => ({
    width: w,
    height: h,
    borderRadius: 8,
    background: "rgba(128,128,128,.14)",
    animation: "graphite-pulse 1.4s ease-in-out infinite",
  });
  return (
    <div
      className={["graphite-chart", className].filter(Boolean).join(" ")}
      aria-busy={rest["aria-busy"]}
      style={{ width: "100%", boxSizing: "border-box", padding: 26, borderRadius: 20, border: "1px solid rgba(128,128,128,.14)", display: "flex", flexDirection: "column", gap: 14 }}
    >
      <style>{"@keyframes graphite-pulse{0%,100%{opacity:1}50%{opacity:.45}}"}</style>
      <div style={bar("30%", 12)} />
      <div style={bar("20%", 30)} />
      <div style={{ display: "flex", alignItems: "flex-end", gap: 10, height: 220, marginTop: 8 }}>
        {[48, 72, 36, 88, 60, 76, 42, 64].map((h, i) => (
          <div key={i} style={{ ...bar("100%", 0), height: `${h}%`, animationDelay: `${i * 80}ms` }} />
        ))}
      </div>
    </div>
  );
}

export const Chart = Object.assign(ChartRoot, { Skeleton: ChartSkeleton });
