// Package haproxy renders the desired configuration into haproxy.cfg.
//
// Output is deterministic: the same snapshot always renders byte-identical
// config (entities keep snapshot order, nothing depends on maps or time).
package haproxy

import (
	"fmt"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

	"github.com/instantoffr/relay/internal/model"
	"github.com/instantoffr/relay/internal/render"
)

// RuntimeSocketName is the HAProxy admin (runtime API / stats) socket inside
// the run dir. It deliberately differs from the agent socket
// (agent.SocketPath(runDir, "haproxy") = <runDir>/haproxy.sock); the haproxy
// agent forwards /v1/runtime commands to this socket.
const RuntimeSocketName = "haproxy-runtime.sock"

// RuntimeSocketPath returns the admin socket path for a run dir.
func RuntimeSocketPath(runDir string) string {
	if runDir == "" {
		runDir = "/run/relay"
	}
	return filepath.Join(runDir, RuntimeSocketName)
}

// CAFile is the trust store used when verifying re-encrypted upstream TLS.
const CAFile = "/etc/ssl/certs/ca-certificates.crt"

// StatsFrontendName is reserved for the built-in stats listener.
const StatsFrontendName = "stats"

// HasBackends reports whether HAProxy should run.
func HasBackends(snap *model.Snapshot) bool { return len(snap.Backends) > 0 }

// Render produces haproxy.cfg.
func Render(snap *model.Snapshot, env render.Env) (string, error) {
	var b strings.Builder
	s := effectiveSettings(snap.HAProxy)

	b.WriteString("# Generated by Relay. Do not edit: changes are overwritten on the next apply.\n\n")

	b.WriteString("global\n")
	b.WriteString("    master-worker\n")
	fmt.Fprintf(&b, "    maxconn %d\n", s.MaxConn)
	b.WriteString("    log stderr format raw local0\n")
	sock := "    stats socket " + RuntimeSocketPath(env.RunDir) + " mode 660 level admin"
	if s.SeamlessReload {
		sock += " expose-fd listeners"
	}
	b.WriteString(sock + "\n")
	b.WriteString("    stats timeout 30s\n")
	b.WriteString("\n")

	b.WriteString("defaults\n")
	b.WriteString("    mode http\n")
	b.WriteString("    log global\n")
	b.WriteString("    option dontlognull\n")
	fmt.Fprintf(&b, "    timeout connect %s\n", s.TimeoutConnect)
	fmt.Fprintf(&b, "    timeout client %s\n", s.TimeoutClient)
	fmt.Fprintf(&b, "    timeout server %s\n", s.TimeoutServer)
	fmt.Fprintf(&b, "    default-server init-addr libc,none inter %s rise %d fall %d\n", s.CheckInterval, s.Rise, s.Fall)
	b.WriteString("\n")

	if s.StatsEnabled && s.StatsBind != "" {
		b.WriteString(renderStats(snap, s))
		b.WriteString("\n")
	}

	for i := range snap.Frontends {
		f := &snap.Frontends[i]
		if !f.Enabled {
			continue
		}
		sec, err := renderFrontend(snap, f)
		if err != nil {
			return "", err
		}
		b.WriteString(sec)
		b.WriteString("\n")
	}

	for i := range snap.Backends {
		b.WriteString(RenderBackend(snap, &snap.Backends[i]))
		b.WriteString("\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// effectiveSettings fills zero values so a partially stored settings document
// still renders a valid config.
func effectiveSettings(s model.HAProxySettings) model.HAProxySettings {
	def := func(v *string, d string) {
		if strings.TrimSpace(*v) == "" {
			*v = d
		}
	}
	def(&s.TimeoutConnect, "5s")
	def(&s.TimeoutClient, "50s")
	def(&s.TimeoutServer, "50s")
	def(&s.CheckInterval, "2s")
	if s.MaxConn <= 0 {
		s.MaxConn = 20000
	}
	if s.Rise <= 0 {
		s.Rise = 2
	}
	if s.Fall <= 0 {
		s.Fall = 3
	}
	return s
}

// ---------------------------------------------------------------- stats

func renderStats(snap *model.Snapshot, s model.HAProxySettings) string {
	var b strings.Builder
	b.WriteString("frontend " + StatsFrontendName + "\n")
	fmt.Fprintf(&b, "    bind %s\n", s.StatsBind)
	b.WriteString("    mode http\n")
	b.WriteString("    no log\n")
	if s.StatsAccessList != "" {
		for _, al := range snap.AccessLists {
			if al.ID == s.StatsAccessList {
				for _, line := range AccessRules(al.Rules) {
					b.WriteString("    " + line + "\n")
				}
				break
			}
		}
	}
	if s.Prometheus {
		b.WriteString("    http-request use-service prometheus-exporter if { path /metrics }\n")
	}
	b.WriteString("    stats enable\n")
	b.WriteString("    stats uri /\n")
	b.WriteString("    stats refresh 10s\n")
	return b.String()
}

// AccessRules turns an access list's ordered allow/deny rules into
// `http-request deny` lines with first-match-wins semantics (like nginx).
func AccessRules(rules []model.IPRule) []string {
	var acls, lines, allows []string
	hasAllow := false
	for i, r := range rules {
		cidr := strings.TrimSpace(r.CIDR)
		if cidr == "" {
			continue
		}
		all := strings.EqualFold(cidr, "all")
		name := fmt.Sprintf("acl_rule_%d", i+1)
		if !all {
			acls = append(acls, fmt.Sprintf("acl %s src %s", name, cidr))
		}
		neg := negations(allows)
		switch r.Action {
		case "allow":
			hasAllow = true
			if all {
				// Everything not denied so far is allowed: stop here.
				return append(acls, lines...)
			}
			allows = append(allows, name)
		case "deny":
			if all {
				if neg == "" {
					lines = append(lines, "http-request deny")
				} else {
					lines = append(lines, "http-request deny if "+neg)
				}
				return append(acls, lines...)
			}
			cond := name
			if neg != "" {
				cond += " " + neg
			}
			lines = append(lines, "http-request deny if "+cond)
		}
	}
	if hasAllow {
		lines = append(lines, "http-request deny if "+negations(allows))
	}
	return append(acls, lines...)
}

func negations(names []string) string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = "!" + n
	}
	return strings.Join(out, " ")
}

// ---------------------------------------------------------------- backends

// ServerName returns the haproxy server name of the i-th server of b.
func ServerName(b *model.Backend, i int) string {
	if i < len(b.Servers) && strings.TrimSpace(b.Servers[i].Name) != "" {
		return b.Servers[i].Name
	}
	return fmt.Sprintf("%s-%d", b.Name, i+1)
}

var balanceAlgos = map[string]string{
	"roundrobin": "roundrobin",
	"leastconn":  "leastconn",
	"source":     "source",
	"uri":        "uri",
	"random":     "random",
	"first":      "first",
	"static-rr":  "static-rr",
}

var (
	statusCodeRe  = regexp.MustCompile(`^[1-5][0-9]{2}$`)
	statusClassRe = regexp.MustCompile(`^([1-5])xx$`)
	statusListRe  = regexp.MustCompile(`^[1-5][0-9]{2}(-[1-5][0-9]{2})?(,[1-5][0-9]{2}(-[1-5][0-9]{2})?)*$`)
)

// RenderBackend renders one backend section.
func RenderBackend(snap *model.Snapshot, bk *model.Backend) string {
	var b strings.Builder
	s := effectiveSettings(snap.HAProxy)
	mode := bk.Mode
	if mode != "tcp" {
		mode = "http"
	}
	hc := bk.HealthCheck

	fmt.Fprintf(&b, "backend %s\n", bk.Name)
	fmt.Fprintf(&b, "    mode %s\n", mode)
	algo := balanceAlgos[bk.Algorithm]
	if algo == "" || (algo == "uri" && mode != "http") {
		algo = "roundrobin"
	}
	fmt.Fprintf(&b, "    balance %s\n", algo)
	if mode == "http" && bk.ForwardClientIP {
		b.WriteString("    option forwardfor\n")
	}

	switch hc.Type {
	case "http":
		method := strings.ToUpper(strings.TrimSpace(hc.Method))
		if method == "" {
			method = "GET"
		}
		path := strings.TrimSpace(hc.Path)
		if path == "" {
			path = "/"
		}
		b.WriteString("    option httpchk\n")
		send := fmt.Sprintf("    http-check send meth %s uri %s", method, quoteArg(path))
		if h := strings.TrimSpace(hc.Host); h != "" {
			send += " ver HTTP/1.1 hdr Host " + quoteArg(h)
		}
		b.WriteString(send + "\n")
		b.WriteString("    http-check expect " + expectStatus(hc.ExpectStatus) + "\n")
	case "pgsql":
		b.WriteString("    option pgsql-check user relay\n")
	case "mysql":
		b.WriteString("    option mysql-check\n")
	case "redis":
		b.WriteString("    option redis-check\n")
	}

	checks := hc.Type != "" && hc.Type != "none"
	if checks {
		inter := strings.TrimSpace(hc.Interval)
		if inter == "" {
			inter = s.CheckInterval
		}
		rise, fall := hc.Rise, hc.Fall
		if rise <= 0 {
			rise = s.Rise
		}
		if fall <= 0 {
			fall = s.Fall
		}
		fmt.Fprintf(&b, "    default-server inter %s rise %d fall %d\n", inter, rise, fall)
	}

	sticky := bk.Sticky.Enabled
	stickyMode := bk.Sticky.Mode
	if sticky {
		if mode != "http" {
			stickyMode = "source"
		}
		switch stickyMode {
		case "source":
			b.WriteString("    stick-table type ip size 200k expire 30m\n")
			b.WriteString("    stick on src\n")
		case "prefix":
			fmt.Fprintf(&b, "    cookie %s prefix nocache\n", cookieName(bk.Sticky.CookieName))
		default:
			stickyMode = "insert"
			fmt.Fprintf(&b, "    cookie %s insert indirect nocache\n", cookieName(bk.Sticky.CookieName))
		}
	}

	if bk.Retries > 0 {
		fmt.Fprintf(&b, "    retries %d\n", bk.Retries)
	}
	if len(bk.Servers) > 1 {
		b.WriteString("    option redispatch\n")
	}
	if v := strings.TrimSpace(bk.Timeouts.Connect); v != "" {
		fmt.Fprintf(&b, "    timeout connect %s\n", v)
	}
	if v := strings.TrimSpace(bk.Timeouts.Server); v != "" {
		fmt.Fprintf(&b, "    timeout server %s\n", v)
	}
	if v := strings.TrimSpace(bk.Timeouts.Queue); v != "" {
		fmt.Fprintf(&b, "    timeout queue %s\n", v)
	}

	for i, srv := range bk.Servers {
		name := ServerName(bk, i)
		line := fmt.Sprintf("    server %s %s", name, hostPort(srv.Address, srv.Port))
		if checks && srv.Check {
			line += " check"
		}
		w := srv.Weight
		if w <= 0 {
			w = 100
		}
		line += " weight " + strconv.Itoa(w)
		if srv.Role == model.ServerBackup {
			line += " backup"
		}
		if sticky && (stickyMode == "insert" || stickyMode == "prefix") {
			line += " cookie " + name
		}
		if bk.SendProxy {
			line += " send-proxy-v2"
		}
		if bk.TLSReencrypt {
			if bk.TLSVerify {
				line += " ssl verify required ca-file " + CAFile
			} else {
				line += " ssl verify none"
			}
		}
		if srv.State == model.ServerStateMaint {
			line += " disabled"
		}
		b.WriteString(line + "\n")
	}
	return b.String()
}

func expectStatus(v string) string {
	v = strings.ToLower(strings.TrimSpace(v))
	switch {
	case v == "":
		return "rstatus ^2"
	case statusCodeRe.MatchString(v):
		return "status " + v
	case statusClassRe.MatchString(v):
		return "rstatus ^" + statusClassRe.FindStringSubmatch(v)[1]
	case statusListRe.MatchString(v):
		return "status " + v
	}
	return "rstatus ^2"
}

func cookieName(n string) string {
	if strings.TrimSpace(n) == "" {
		return "SRVID"
	}
	return n
}

func hostPort(addr string, port int) string {
	addr = strings.TrimSpace(addr)
	if strings.Contains(addr, ":") && !strings.HasPrefix(addr, "[") {
		addr = "[" + addr + "]"
	}
	return addr + ":" + strconv.Itoa(port)
}

// ---------------------------------------------------------------- frontends

// RenderFrontend renders one frontend section (regardless of Enabled).
// Rules pointing at unknown backends are rendered with a comment.
func RenderFrontend(snap *model.Snapshot, f *model.Frontend) string {
	out, err := renderFrontend(snap, f)
	if err != nil {
		return out + "    # error: " + err.Error() + "\n"
	}
	return out
}

func renderFrontend(snap *model.Snapshot, f *model.Frontend) (string, error) {
	var b strings.Builder
	mode := f.Mode
	if mode != "tcp" {
		mode = "http"
	}
	backendName := func(id string) (string, bool) {
		for i := range snap.Backends {
			if snap.Backends[i].ID == id {
				return snap.Backends[i].Name, true
			}
		}
		return "", false
	}

	fmt.Fprintf(&b, "frontend %s\n", f.Name)
	bind := "    bind " + f.Bind
	if f.AcceptProxy {
		bind += " accept-proxy"
	}
	b.WriteString(bind + "\n")
	fmt.Fprintf(&b, "    mode %s\n", mode)
	if mode == "http" {
		b.WriteString("    option httplog\n")
		if f.HostID != "" {
			// Fed by the reverse proxy: nginx already sets X-Forwarded-For.
			b.WriteString("    option forwardfor except 127.0.0.0/8\n")
		}
		if f.Compression {
			b.WriteString("    compression algo gzip\n")
			b.WriteString("    compression type text/html text/plain text/css application/json application/javascript\n")
		}
	} else {
		b.WriteString("    option tcplog\n")
	}

	usesSNI := false
	for _, r := range f.Rules {
		for _, c := range r.Conditions {
			if c.Type == model.CondSNI {
				usesSNI = true
			}
		}
	}
	if mode == "tcp" && usesSNI {
		b.WriteString("    tcp-request inspect-delay 5s\n")
		b.WriteString("    tcp-request content accept if { req_ssl_hello_type 1 }\n")
	}

	var acls, uses []string
	var firstErr error
	for i, r := range f.Rules {
		if len(r.Conditions) == 0 {
			continue
		}
		name, ok := backendName(r.BackendID)
		if !ok {
			if firstErr == nil {
				firstErr = fmt.Errorf("frontend %s rule %d: backend %q does not exist", f.Name, i+1, r.BackendID)
			}
			continue
		}
		var conds []string
		for j, c := range r.Conditions {
			acl := fmt.Sprintf("r%d_%s", i+1, condLabel(c, j))
			acls = append(acls, fmt.Sprintf("acl %s %s", acl, conditionExpr(c)))
			if c.Negate {
				conds = append(conds, "!"+acl)
			} else {
				conds = append(conds, acl)
			}
		}
		uses = append(uses, fmt.Sprintf("use_backend %s if %s", name, strings.Join(conds, " ")))
	}
	for _, l := range acls {
		b.WriteString("    " + l + "\n")
	}
	for _, l := range uses {
		b.WriteString("    " + l + "\n")
	}
	if f.DefaultBackendID != "" {
		if name, ok := backendName(f.DefaultBackendID); ok {
			fmt.Fprintf(&b, "    default_backend %s\n", name)
		} else if firstErr == nil {
			firstErr = fmt.Errorf("frontend %s: default backend %q does not exist", f.Name, f.DefaultBackendID)
		}
	}
	return b.String(), firstErr
}

func condLabel(c model.Condition, j int) string {
	t := c.Type
	switch t {
	case model.CondPathBeg:
		t = "path_beg"
	case model.CondPathRegex:
		t = "path_reg"
	case "":
		t = "cond"
	}
	return fmt.Sprintf("%s_%d", t, j+1)
}

func conditionExpr(c model.Condition) string {
	v := strings.TrimSpace(c.Value)
	switch c.Type {
	case model.CondHost:
		h := strings.ToLower(v)
		if strings.HasPrefix(h, "*.") {
			return "req.hdr(host),host_only -m end -i " + quoteArg(h[1:])
		}
		return "req.hdr(host),host_only -m str -i " + quoteArg(h)
	case model.CondPathBeg:
		return "path_beg " + quoteArg(v)
	case model.CondPath:
		return "path " + quoteArg(v)
	case model.CondPathRegex:
		return "path_reg " + quoteArg(v)
	case model.CondHeader:
		name := strings.TrimSpace(c.Name)
		if v == "" {
			return fmt.Sprintf("req.hdr(%s) -m found", name)
		}
		return fmt.Sprintf("req.hdr(%s) -m str %s", name, quoteArg(v))
	case model.CondSrc:
		parts := strings.FieldsFunc(v, func(r rune) bool { return r == ',' || r == ' ' })
		return "src " + strings.Join(parts, " ")
	case model.CondSNI:
		h := strings.ToLower(v)
		if strings.HasPrefix(h, "*.") {
			return "req.ssl_sni -m end -i " + quoteArg(h[1:])
		}
		return "req.ssl_sni -m str -i " + quoteArg(h)
	}
	return "always_false"
}

var plainArg = regexp.MustCompile(`^[A-Za-z0-9._/:*~%@+=,^$\-\[\]()|?]+$`)

// quoteArg single-quotes a config argument when it contains characters with
// special meaning to the haproxy config parser. Single quotes disable all
// interpretation (no escapes, no environment variable expansion); values
// containing a single quote are rejected by validation.
func quoteArg(v string) string {
	if v != "" && plainArg.MatchString(v) && !strings.ContainsAny(v, `#"'\`) {
		return v
	}
	return "'" + strings.ReplaceAll(v, "'", "") + "'"
}
